import PDFDocument from "pdfkit";
import type { InventoryItemDTO, InventorySummaryDTO } from "@/types/radar";

export type InventoryPdfMode = "client" | "internal";

type InventoryPdfOptions = {
  mode: InventoryPdfMode;
  items: InventoryItemDTO[];
  summary: InventorySummaryDTO;
  generatedAt?: Date;
};

const page = {
  margin: 42,
  width: 612,
  height: 792,
  bottom: 734
};

function money(value: number | null | undefined) {
  if (value === null || value === undefined || Number.isNaN(value)) return "TBD";
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
}

function labelize(value: string | null | undefined) {
  if (!value) return "Uncategorized";
  return value
    .toLowerCase()
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function generatedDate(date: Date) {
  return new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric" }).format(date);
}

function fileDate(date: Date) {
  return date.toISOString().slice(0, 10);
}

function availabilityStatus(item: InventoryItemDTO) {
  if (item.quantityOwned <= 0) return { label: "Sold Out", color: "#dc2626", fill: "#fee2e2" };
  if (item.quantityOwned <= 2) return { label: "Low Stock", color: "#b45309", fill: "#fef3c7" };
  return { label: "In Stock", color: "#047857", fill: "#d1fae5" };
}

function itemIdentifier(item: InventoryItemDTO) {
  return item.upc || item.sku || item.dpci || item.asin || "Identifier not saved";
}

function clientPrice(item: InventoryItemDTO) {
  return item.targetSellPrice ?? null;
}

function clientNote(item: InventoryItemDTO) {
  return item.description || item.condition || null;
}

function truncate(value: string, max = 120) {
  return value.length > max ? `${value.slice(0, max - 1)}...` : value;
}

async function fetchImageBuffer(url: string | null | undefined) {
  if (!url || !/^https?:\/\//i.test(url)) return null;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 1400);
  try {
    const response = await fetch(url, { signal: controller.signal });
    if (!response.ok) return null;
    const contentType = response.headers.get("content-type") || "";
    if (!/image\/(png|jpe?g)/i.test(contentType)) return null;
    const arrayBuffer = await response.arrayBuffer();
    if (arrayBuffer.byteLength > 1_200_000) return null;
    return Buffer.from(arrayBuffer);
  } catch {
    return null;
  } finally {
    clearTimeout(timeout);
  }
}

async function loadImageMap(items: InventoryItemDTO[]) {
  const imageMap = new Map<string, Buffer>();
  const uniqueItems = items.filter((item, index, all) => item.imageUrl && all.findIndex((candidate) => candidate.imageUrl === item.imageUrl) === index);
  let cursor = 0;
  const workers = Array.from({ length: Math.min(4, uniqueItems.length) }, async () => {
    while (cursor < uniqueItems.length) {
      const item = uniqueItems[cursor++];
      const image = await fetchImageBuffer(item.imageUrl);
      if (image) {
        for (const matching of items.filter((candidate) => candidate.imageUrl === item.imageUrl)) {
          imageMap.set(matching.id, image);
        }
      }
    }
  });
  await Promise.all(workers);
  return imageMap;
}

function drawFooter(doc: PDFKit.PDFDocument, pageNumber: number) {
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#64748b")
    .text("Generated by Poke Radar - Availability subject to change.", page.margin, page.height - 34, {
      width: 360,
      lineBreak: false
    })
    .text(`Page ${pageNumber}`, page.width - page.margin - 70, page.height - 34, {
      width: 70,
      align: "right",
      lineBreak: false
    });
}

function addPage(doc: PDFKit.PDFDocument, state: { pageNumber: number }) {
  if (doc.page) drawFooter(doc, state.pageNumber);
  doc.addPage({ size: "LETTER", margin: page.margin });
  state.pageNumber += 1;
}

function drawHeader(doc: PDFKit.PDFDocument, options: InventoryPdfOptions) {
  const generatedAt = options.generatedAt ?? new Date();
  doc.rect(0, 0, page.width, 112).fill("#071014");
  doc
    .fillColor("#22c55e")
    .font("Helvetica-Bold")
    .fontSize(14)
    .text("POKE RADAR", page.margin, 35, { characterSpacing: 0.8 })
    .fillColor("#ffffff")
    .fontSize(26)
    .text(options.mode === "client" ? "Inventory Catalog" : "Internal Inventory Report", page.margin, 55)
    .fillColor("#cbd5e1")
    .font("Helvetica")
    .fontSize(10)
    .text(options.mode === "client" ? "Available Products" : "Cost, stock, sales, and profit/loss", page.margin, 86);

  doc
    .roundedRect(page.width - page.margin - 170, 34, 170, 48, 12)
    .fillAndStroke("#0f1b22", "#1f4030")
    .fillColor("#94a3b8")
    .font("Helvetica")
    .fontSize(8)
    .text("Generated", page.width - page.margin - 156, 45)
    .fillColor("#ffffff")
    .font("Helvetica-Bold")
    .fontSize(11)
    .text(generatedDate(generatedAt), page.width - page.margin - 156, 59, { width: 140 });
}

function drawSummary(doc: PDFKit.PDFDocument, options: InventoryPdfOptions, y: number) {
  const categories = new Set(options.items.map((item) => item.category)).size;
  const available = options.items.reduce((sum, item) => sum + Math.max(0, item.quantityOwned), 0);
  const metrics =
    options.mode === "client"
      ? [
          { label: "Products Available", value: String(options.items.length) },
          { label: "Items In Stock", value: String(available) },
          { label: "Categories", value: String(categories) }
        ]
      : [
          { label: "Products", value: String(options.items.length) },
          { label: "Items Owned", value: String(options.summary.itemsOwned) },
          { label: "Total Cost", value: money(options.summary.totalCost) },
          { label: "Net P/L", value: money(options.summary.netProfitLoss) }
        ];
  const gap = 10;
  const boxWidth = (page.width - page.margin * 2 - gap * (metrics.length - 1)) / metrics.length;
  metrics.forEach((metric, index) => {
    const x = page.margin + index * (boxWidth + gap);
    doc.roundedRect(x, y, boxWidth, 54, 12).fillAndStroke("#ffffff", "#d9e4df");
    doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(14).text(metric.value, x + 12, y + 13, { width: boxWidth - 24 });
    doc.fillColor("#64748b").font("Helvetica").fontSize(8).text(metric.label, x + 12, y + 32, { width: boxWidth - 24 });
  });
  return y + 76;
}

function drawPlaceholder(doc: PDFKit.PDFDocument, x: number, y: number, size: number) {
  doc.roundedRect(x, y, size, size, 8).fillAndStroke("#eef6f2", "#d9e4df");
  doc.fillColor("#16a34a").font("Helvetica-Bold").fontSize(12).text("PR", x, y + size / 2 - 7, { width: size, align: "center" });
}

function drawProductImage(doc: PDFKit.PDFDocument, image: Buffer | undefined, x: number, y: number, size: number) {
  if (!image) {
    drawPlaceholder(doc, x, y, size);
    return;
  }
  try {
    doc.roundedRect(x, y, size, size, 8).fillAndStroke("#f8fafc", "#d9e4df");
    doc.image(image, x + 5, y + 5, { fit: [size - 10, size - 10], align: "center", valign: "center" });
  } catch {
    drawPlaceholder(doc, x, y, size);
  }
}

function drawBadge(doc: PDFKit.PDFDocument, label: string, x: number, y: number, color: string, fill: string, width = 58) {
  doc.roundedRect(x, y, width, 16, 8).fill(fill);
  doc.fillColor(color).font("Helvetica-Bold").fontSize(7).text(label, x + 6, y + 5, { width: width - 12, align: "center", lineBreak: false });
}

function ensureSpace(doc: PDFKit.PDFDocument, state: { pageNumber: number }, y: number, needed: number) {
  if (y + needed <= page.bottom) return y;
  addPage(doc, state);
  return page.margin;
}

function drawClientCard(doc: PDFKit.PDFDocument, item: InventoryItemDTO, image: Buffer | undefined, x: number, y: number, width: number) {
  const height = 140;
  const status = availabilityStatus(item);
  doc.roundedRect(x, y, width, height, 12).fillAndStroke("#ffffff", "#d9e4df");
  drawProductImage(doc, image, x + 12, y + 16, 58);
  const textX = x + 82;
  const textWidth = width - 94;
  doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(10).text(truncate(item.itemName, 95), textX, y + 15, {
    width: textWidth,
    height: 30,
    ellipsis: true
  });
  doc.fillColor("#64748b").font("Helvetica").fontSize(8).text(labelize(item.category), textX, y + 49, { width: textWidth });
  doc.fillColor("#334155").font("Helvetica").fontSize(8).text(`UPC/SKU: ${itemIdentifier(item)}`, textX, y + 64, { width: textWidth, ellipsis: true });
  doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(9).text(`Available: ${item.quantityOwned}`, textX, y + 82, { width: 88 });
  drawBadge(doc, status.label, textX + 96, y + 80, status.color, status.fill, 62);
  const price = clientPrice(item);
  if (price !== null) {
    doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(9).text(`Price: ${money(price)}`, textX, y + 104, { width: textWidth });
  }
  const note = clientNote(item);
  if (note) {
    doc.fillColor("#64748b").font("Helvetica").fontSize(7).text(truncate(note, 90), textX, y + 119, { width: textWidth, height: 12, ellipsis: true });
  }
  return height;
}

function drawClientCatalog(doc: PDFKit.PDFDocument, state: { pageNumber: number }, items: InventoryItemDTO[], imageMap: Map<string, Buffer>, startY: number) {
  let y = startY;
  let column = 0;
  const gap = 14;
  const cardWidth = (page.width - page.margin * 2 - gap) / 2;
  const cardHeight = 140;
  for (const item of items) {
    if (column === 0) y = ensureSpace(doc, state, y, cardHeight + 12);
    const x = page.margin + column * (cardWidth + gap);
    drawClientCard(doc, item, imageMap.get(item.id), x, y, cardWidth);
    if (column === 0) {
      column = 1;
    } else {
      column = 0;
      y += cardHeight + 12;
    }
  }
  return column === 0 ? y : y + cardHeight + 12;
}

function drawNoItems(doc: PDFKit.PDFDocument, y: number) {
  doc.roundedRect(page.margin, y, page.width - page.margin * 2, 90, 14).fillAndStroke("#ffffff", "#d9e4df");
  doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(14).text("No matching inventory", page.margin + 18, y + 24);
  doc.fillColor("#64748b").font("Helvetica").fontSize(9).text("No products matched this export filter.", page.margin + 18, y + 47);
}

function drawInternalHeader(doc: PDFKit.PDFDocument, y: number) {
  const columns = [
    ["Product", 170],
    ["Qty", 34],
    ["Avg Cost", 62],
    ["Total Cost", 66],
    ["Sold", 36],
    ["Profit/Loss", 72],
    ["Status", 64]
  ] as const;
  let x = page.margin;
  doc.rect(page.margin, y, page.width - page.margin * 2, 22).fill("#0f172a");
  doc.fillColor("#ffffff").font("Helvetica-Bold").fontSize(7);
  for (const [label, width] of columns) {
    doc.text(label, x + 6, y + 8, { width: width - 8, lineBreak: false });
    x += width;
  }
}

function drawInternalTable(doc: PDFKit.PDFDocument, state: { pageNumber: number }, items: InventoryItemDTO[], startY: number) {
  let y = startY;
  drawInternalHeader(doc, y);
  y += 22;
  const rowHeight = 42;
  for (const item of items) {
    y = ensureSpace(doc, state, y, rowHeight + 26);
    if (y === page.margin) {
      drawInternalHeader(doc, y);
      y += 22;
    }
    const status = availabilityStatus(item);
    doc.rect(page.margin, y, page.width - page.margin * 2, rowHeight).fill(y % 2 ? "#ffffff" : "#f8fafc");
    let x = page.margin;
    doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(8).text(truncate(item.itemName, 70), x + 6, y + 8, { width: 164, height: 18, ellipsis: true });
    doc.fillColor("#64748b").font("Helvetica").fontSize(7).text(itemIdentifier(item), x + 6, y + 26, { width: 164, height: 9, ellipsis: true });
    x += 170;
    doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(8).text(String(item.quantityOwned), x + 6, y + 15, { width: 28 });
    x += 34;
    doc.font("Helvetica").text(money(item.averageCost), x + 6, y + 15, { width: 56 });
    x += 62;
    doc.text(money(item.averageCost * item.quantityOwned), x + 6, y + 15, { width: 60 });
    x += 66;
    doc.text(String(item.quantitySold), x + 6, y + 15, { width: 30 });
    x += 36;
    doc.fillColor((item.realizedProfitLoss ?? 0) >= 0 ? "#047857" : "#dc2626").font("Helvetica-Bold").text(money(item.realizedProfitLoss), x + 6, y + 15, { width: 66 });
    x += 72;
    drawBadge(doc, status.label, x + 6, y + 13, status.color, status.fill, 56);
    y += rowHeight;
  }
  return y;
}

export function inventoryPdfFilename(mode: InventoryPdfMode, generatedAt = new Date()) {
  return `poke-radar-inventory-${mode}-${fileDate(generatedAt)}.pdf`;
}

export async function renderInventoryPdf(options: InventoryPdfOptions) {
  const generatedAt = options.generatedAt ?? new Date();
  const doc = new PDFDocument({ autoFirstPage: false, size: "LETTER", margin: page.margin, bufferPages: false });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk: Buffer) => chunks.push(chunk));
  const done = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const imageMap = options.mode === "client" ? await loadImageMap(options.items) : new Map<string, Buffer>();
  const state = { pageNumber: 0 };
  addPage(doc, state);
  drawHeader(doc, { ...options, generatedAt });
  const y = drawSummary(doc, { ...options, generatedAt }, 132);

  if (!options.items.length) {
    drawNoItems(doc, y);
  } else if (options.mode === "client") {
    drawClientCatalog(doc, state, options.items, imageMap, y);
  } else {
    drawInternalTable(doc, state, options.items, y);
  }

  drawFooter(doc, state.pageNumber);
  doc.end();
  return done;
}
