import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

test("iPad POS cart keeps variable content inside explicit scroll and grid boundaries", () => {
  const layout = readFileSync(path.join(root, "src/app/pos/layout.tsx"), "utf8");
  const css = readFileSync(path.join(root, "src/app/pos/pos-ipad-cart-overflow.module.css"), "utf8");

  assert.match(layout, /pos-ipad-cart-overflow\.module\.css/);
  assert.match(layout, /overflowStyles\.cartOverflowFix/);
  assert.match(css, /\.pos-cart-panel\)[\s\S]*display: flex !important/);
  assert.match(css, /\.pos-cart-panel\)[\s\S]*overflow: hidden !important/);
  assert.match(css, /\.pos-cart-lines:not\(\.is-empty\)/);
  assert.match(css, /\.pos-cart-lines:not\(\.is-empty\)[\s\S]*flex: 1 1 auto !important/);
  assert.match(css, /\.pos-cart-lines:not\(\.is-empty\)[\s\S]*overflow-y: auto !important/);
  assert.doesNotMatch(css, /Current Sale uses ONE vertical scroll surface/);
  assert.doesNotMatch(css, /\.pos-cart-lines:not\(\.is-empty\)[\s\S]*overflow: visible !important/);
  assert.match(css, /grid-template-columns: 48px minmax\(0, 1fr\) 108px 34px !important/);
  assert.match(css, /> \.pos-cart-line-copy/);
  assert.match(css, /> \.pos-cart-quantity/);
  assert.match(css, /> \.pos-line-total/);
  assert.match(css, /> \.icon-button\.small/);
  assert.match(css, /\.pos-customer-results/);
  assert.match(css, /-webkit-overflow-scrolling: touch/);
});

test("iPad POS sale screen keeps the Charge footer inside the visible viewport", () => {
  const layout = readFileSync(path.join(root, "src/app/pos/layout.tsx"), "utf8");
  const manifest = readFileSync(path.join(root, "public/manifest-pos.webmanifest"), "utf8");
  const flow = readFileSync(path.join(root, "src/app/pos/PosSquareLikeFlow.tsx"), "utf8");
  const flowCss = readFileSync(path.join(root, "src/app/pos/PosSquareLikeFlow.module.css"), "utf8");
  const guard = readFileSync(path.join(root, "src/app/pos/PosSaleViewportGuard.tsx"), "utf8");
  const pwaGuard = readFileSync(path.join(root, "src/app/pos/PosPwaCacheGuard.tsx"), "utf8");
  const page = readFileSync(path.join(root, "src/app/pos/page.tsx"), "utf8");
  const serviceWorker = readFileSync(path.join(root, "public/sw.js"), "utf8");
  const viewportQa = readFileSync(path.join(root, "scripts/pos-viewport-qa.ts"), "utf8");
  const shell = readFileSync(path.join(root, "src/app/pos/PosRegisterShell.tsx"), "utf8");
  const visibleGuard = readFileSync(path.join(root, "src/app/pos/PosVisibleViewport.tsx"), "utf8");
  const viewportHelper = readFileSync(path.join(root, "src/app/pos/posViewport.ts"), "utf8");
  const guardCss = readFileSync(path.join(root, "src/app/pos/pos-sale-viewport-guard.module.css"), "utf8");

  assert.match(layout, /import \{ PosSaleViewportGuard \} from "\.\/PosSaleViewportGuard"/);
  assert.match(layout, /import \{ PosPwaCacheGuard \} from "\.\/PosPwaCacheGuard"/);
  assert.match(layout, /import saleViewportGuardStyles from "\.\/pos-sale-viewport-guard\.module\.css"/);
  assert.match(layout, /cartTitleLayoutStyles\.cartTitleLayout\} \$\{saleViewportGuardStyles\.saleViewportGuard\}/);
  assert.match(layout, /<PosPwaCacheGuard \/>[\s\S]*<PosVisibleViewport \/>/);
  assert.match(layout, /<PosVisibleViewport \/>[\s\S]*<PosSaleViewportGuard \/>/);
  assert.match(layout, /<PosSaleViewportGuard \/>[\s\S]*<PosRegisterShell>\{children\}<\/PosRegisterShell>/);

  assert.match(pwaGuard, /display-mode: standalone/);
  assert.match(pwaGuard, /navigatorWithStandalone\.standalone/);
  assert.match(layout, /"apple-mobile-web-app-capable": "yes"/);
  assert.match(manifest, /"start_url": "\/pos\?source=pos-pwa"/);
  assert.match(manifest, /"scope": "\/pos"/);
  assert.match(manifest, /"display_override": \["standalone"\]/);
  assert.match(pwaGuard, /BUILD_INFO\.serviceWorkerVersion/);
  assert.match(pwaGuard, /navigator\.serviceWorker\.register\(SERVICE_WORKER_PATH, \{ updateViaCache: "none" \}\)/);
  assert.match(pwaGuard, /registration\.active\?\.postMessage\(\{ type: "CLEAR_APP_CACHE" \}\)/);
  assert.match(pwaGuard, /key\.startsWith\(APP_CACHE_PREFIX\)/);
  assert.match(pwaGuard, /storageSet\(window\.localStorage, POS_PWA_CACHE_VERSION_KEY, version\)/);
  assert.match(pwaGuard, /posPwaRefresh/);
  assert.match(pwaGuard, /window\.location\.replace/);
  assert.match(serviceWorker, /poke-radar-sw-2026-08-29-pos-install-v10/);
  assert.match(serviceWorker, /refreshPosClients/);
  assert.match(serviceWorker, /client\.navigate\(url\.toString\(\)\)/);
  assert.match(viewportQa, /\/pos\?source=pos-pwa/);
  assert.doesNotMatch(viewportQa, /expected fixed/);
  assert.match(viewportQa, /body\.position === "fixed"/);

  assert.match(viewportHelper, /export function isPosHomeScreenMode/);
  assert.match(viewportHelper, /export function getUsableViewportHeight/);
  assert.match(viewportHelper, /export function getUsableViewportWidth/);
  assert.match(viewportHelper, /display-mode: standalone/);
  assert.match(viewportHelper, /navigatorWithStandalone\.standalone/);
  assert.match(viewportHelper, /launchedFromPosShortcut/);
  assert.match(viewportHelper, /window\.navigator\.maxTouchPoints > 1/);
  assert.match(viewportHelper, /Math\.min\(\.\.\.availableHeights\)/);
  assert.match(viewportHelper, /Math\.min\(\.\.\.availableWidths\)/);
  assert.doesNotMatch(viewportHelper, /Math\.max\(window\.innerHeight/);
  assert.doesNotMatch(viewportHelper, /Math\.max\(window\.innerWidth/);

  assert.match(visibleGuard, /import \{ getUsableViewportHeight, isPosHomeScreenMode \} from "\.\/posViewport"/);
  assert.match(visibleGuard, /const LOCK_ATTRIBUTE = "data-pos-viewport-locked"/);
  assert.match(visibleGuard, /const HOME_SCREEN_ATTRIBUTE = "data-pos-home-screen"/);
  assert.match(visibleGuard, /return getUsableViewportHeight\(\)/);
  assert.match(visibleGuard, /const ALLOWED_SCROLL_SELECTOR/);
  assert.match(visibleGuard, /\.pos-result-grid/);
  assert.match(visibleGuard, /\.pos-cart-lines:not\(\.is-empty\)/);
  assert.match(visibleGuard, /document\.addEventListener\("touchmove", lockBodyTouch, \{ passive: false \}\)/);
  assert.match(visibleGuard, /closestAllowedScroller/);
  assert.match(visibleGuard, /event\.preventDefault\(\)/);
  assert.match(visibleGuard, /\[data-pos-register-view="checkout"\]\[data-pos-authenticated="true"\]/);
  assert.match(visibleGuard, /root\.setAttribute\(LOCK_ATTRIBUTE, "true"\)/);
  assert.match(visibleGuard, /body\.setAttribute\(LOCK_ATTRIBUTE, "true"\)/);
  assert.match(visibleGuard, /body\.setAttribute\(HOME_SCREEN_ATTRIBUTE, "true"\)/);
  assert.match(visibleGuard, /window\.scrollTo\(0, 0\)/);
  assert.match(visibleGuard, /new MutationObserver\(sync\)/);
  assert.match(visibleGuard, /attributeFilter: \["class", "data-pos-authenticated", "data-pos-register-view"\]/);
  assert.match(visibleGuard, /window\.addEventListener\("scroll", sync/);
  assert.match(visibleGuard, /setViewportLock\(false\)/);

  assert.match(guard, /const CSS_VARIABLE = "--pos-sale-visible-height"/);
  assert.match(guard, /const WORKSPACE_VARIABLE = "--pos-sale-workspace-height"/);
  assert.match(guard, /const ROOT_VARIABLE = "--pos-sale-root-height"/);
  assert.match(guard, /const MIN_PANEL_HEIGHT = 320/);
  assert.match(guard, /const MIN_WORKSPACE_HEIGHT = 420/);
  assert.match(page, /data-pos-store-mode="true"/);
  assert.match(shell, /data-pos-checkout-host=\{user \? "true" : undefined\}/);
  assert.match(shell, /data-pos-square-flow-mode=\{user && view === "checkout" \? "sale" : undefined\}/);

  assert.match(guard, /const BOTTOM_GAP = 64/);
  assert.match(guard, /import \{ getUsableViewportHeight \} from "\.\/posViewport"/);
  assert.match(guard, /function viewportHeight/);
  assert.match(guard, /return getUsableViewportHeight\(\)/);
  assert.doesNotMatch(guard, /function isHomeScreenMode/);
  assert.doesNotMatch(guard, /Math\.max\(window\.innerHeight, viewport\.height\)/);
  assert.doesNotMatch(guard, /viewport\.offsetTop \+ viewport\.height/);
  assert.match(guard, /root\.dataset\.posSquareFlowMode !== "sale"/);
  assert.match(guard, /workspace\.getBoundingClientRect\(\)\.top/);
  assert.match(guard, /panel\.getBoundingClientRect\(\)\.top/);
  assert.match(guard, /root\.style\.setProperty\(ROOT_VARIABLE/);
  assert.match(guard, /workspace\.style\.setProperty\(WORKSPACE_VARIABLE/);
  assert.match(guard, /panel\.style\.setProperty\(CSS_VARIABLE/);
  assert.match(guard, /window\.visualViewport\?\.addEventListener\("resize", sync/);
  assert.match(guard, /window\.visualViewport\?\.addEventListener\("scroll", sync/);

  assert.match(guardCss, /Final sale-screen viewport boundary/);
  assert.match(guardCss, /\.saleViewportGuard \{[\s\S]*height: var\(--pos-visible-height, 100dvh\)/);
  assert.match(guardCss, /\.saleViewportGuard \{[\s\S]*max-height: var\(--pos-visible-height, 100dvh\)/);
  assert.match(guardCss, /\.saleViewportGuard \{[\s\S]*overflow: hidden/);
  assert.match(guardCss, /html\[data-pos-viewport-locked="true"\]/);
  assert.match(guardCss, /body\[data-pos-viewport-locked="true"\]/);
  assert.match(guardCss, /body\[data-pos-viewport-locked="true"\]\)[\s\S]*position: static !important/);
  assert.doesNotMatch(guardCss, /body\[data-pos-viewport-locked="true"\]\)[\s\S]*position: fixed !important/);
  assert.match(guardCss, /body\[data-pos-viewport-locked="true"\]\[data-pos-home-screen="true"\]\)[\s\S]*position: static !important/);
  assert.match(guardCss, /\[data-pos-register-view="checkout"\]\[data-pos-authenticated="true"\]\)[\s\S]*height: var\(--pos-sale-root-height, var\(--pos-visible-height, 100dvh\)\) !important/);
  assert.match(guardCss, /\[data-pos-register-view="checkout"\]\[data-pos-authenticated="true"\]\)[\s\S]*overflow: hidden !important/);
  assert.match(guardCss, /\[data-pos-checkout-host="true"\][\s\S]*height: 100% !important/);
  assert.match(guardCss, /\[data-pos-store-mode="true"\][\s\S]*height: 100% !important/);
  assert.match(guardCss, /\[data-pos-store-mode="true"\] \.app-shell\)[\s\S]*overflow: hidden !important/);
  assert.match(guardCss, /\[data-pos-register-view="checkout"\]\[data-pos-authenticated="true"\] \.app-main\)[\s\S]*height: var\(--pos-sale-root-height, var\(--pos-visible-height, 100dvh\)\) !important/);
  assert.match(guardCss, /\[data-pos-register-view="checkout"\]\[data-pos-authenticated="true"\] \.app-main\)[\s\S]*overflow: hidden !important/);
  assert.match(guardCss, /\[data-pos-register-view="checkout"\]\[data-pos-authenticated="true"\] \.pos-page\)/);
  assert.match(guardCss, /\[data-pos-register-view="checkout"\]\[data-pos-authenticated="true"\] \.pos-workspace\)[\s\S]*overflow: hidden !important/);
  assert.match(guardCss, /height: var\(--pos-sale-workspace-height, 100%\) !important/);
  assert.match(guardCss, /Last-word iPad app frame/);
  assert.match(guardCss, /\.saleViewportGuard\.saleViewportGuard[\s\S]*\[data-pos-store-mode="true"\] \.app-main/);
  assert.match(guardCss, /\.saleViewportGuard\.saleViewportGuard[\s\S]*\[data-pos-square-flow-mode="sale"\] \.pos-workspace/);
  assert.match(guardCss, /\.saleViewportGuard\.saleViewportGuard[\s\S]*\.pos-cart-panel > \[aria-label="Checkout action"\]/);
  assert.match(guardCss, /\[data-pos-register-view="checkout"\]\[data-pos-authenticated="true"\]\[data-pos-square-flow-mode="sale"\] \.pos-search-panel\)[\s\S]*display: flex !important/);
  assert.match(guardCss, /\[data-pos-register-view="checkout"\]\[data-pos-authenticated="true"\]\[data-pos-square-flow-mode="sale"\] \.pos-search-panel\)[\s\S]*overflow: hidden !important/);
  assert.match(guardCss, /\.pos-result-grid\)[\s\S]*flex: 1 1 auto !important/);
  assert.match(guardCss, /\.pos-result-grid\)[\s\S]*overflow-y: auto !important/);
  assert.match(guardCss, /data-pos-authenticated="true"\]\[data-pos-square-flow-mode="sale"\] \.pos-cart-panel/);
  assert.match(guardCss, /height: var\(--pos-sale-visible-height, 100%\) !important/);
  assert.match(guardCss, /max-height: var\(--pos-sale-visible-height, 100%\) !important/);
  assert.match(guardCss, /display: flex !important/);
  assert.match(guardCss, /flex-direction: column !important/);
  assert.match(guardCss, /\.pos-cart-panel\)[\s\S]*overflow: hidden !important/);
  assert.match(guardCss, /\.pos-cart-panel\)[\s\S]*-webkit-overflow-scrolling: touch/);
  assert.match(guardCss, /\.pos-cart-panel\)[\s\S]*touch-action: pan-y/);
  assert.match(guardCss, /\.pos-cart-panel\)[\s\S]*padding-bottom: max\(14px/);
  assert.match(guardCss, /\.pos-cart-lines:not\(\.is-empty\)[\s\S]*flex: 1 1 auto !important/);
  assert.match(guardCss, /\.pos-cart-lines:not\(\.is-empty\)[\s\S]*overflow-y: auto !important/);
  assert.match(guardCss, /\.pos-cart-lines:not\(\.is-empty\)[\s\S]*-webkit-overflow-scrolling: touch/);
  assert.match(guardCss, /\.pos-cart-line\)[\s\S]*grid-template-rows: minmax\(52px, auto\) minmax\(64px, auto\) auto !important/);
  assert.match(guardCss, /\.pos-cart-line\)[\s\S]*grid-auto-rows: auto !important/);
  assert.match(guardCss, /\.pos-cart-line\)[\s\S]*overflow: visible !important/);
  assert.match(guardCss, /\.pos-cart-line > \.pos-cart-line-copy\)[\s\S]*overflow: visible !important/);
  assert.match(guardCss, /\.pos-cart-line > \.pos-cart-line-copy > \.pos-line-price-stack\)[\s\S]*overflow: visible !important/);
  assert.match(guardCss, /\.pos-cart-line > \.pos-cart-line-copy > \.pos-line-actions\)[\s\S]*overflow: visible !important/);
  assert.match(guardCss, /\.pos-cart-panel > \[aria-label="Checkout action"\][\s\S]*flex: 0 0 auto !important/);
  assert.match(guardCss, /\.pos-cart-panel > \[aria-label="Checkout action"\][\s\S]*min-height: 66px !important/);
  assert.match(guardCss, /\.pos-cart-panel > \[aria-label="Checkout action"\][\s\S]*position: sticky !important/);
  assert.match(guardCss, /\.pos-cart-panel > \[aria-label="Checkout action"\][\s\S]*bottom: 0 !important/);
  assert.match(guardCss, /\.pos-cart-panel > \[aria-label="Checkout action"\][\s\S]*width: 100% !important/);
  assert.match(guardCss, /\.pos-cart-panel > \[aria-label="Checkout action"\][\s\S]*max-width: none !important/);
  assert.match(guardCss, /\.pos-cart-panel > \[aria-label="Checkout action"\][\s\S]*transform: none !important/);
  assert.doesNotMatch(guardCss, /\.pos-cart-panel > \[aria-label="Checkout action"\][\s\S]*position: fixed !important/);
  assert.match(guardCss, /@media \(min-width: 740px\) and \(max-width: 999px\)/);
  assert.match(guardCss, /@media \(min-width: 740px\) and \(max-width: 999px\)[\s\S]*\.pos-workspace\)[\s\S]*grid-template-columns: minmax\(0, 1fr\) minmax\(320px, 0\.82fr\) !important/);
  assert.match(guardCss, /@media \(max-width: 739px\)[\s\S]*\.pos-workspace\)[\s\S]*grid-template-rows: minmax\(0, 1fr\) minmax\(300px, 46%\) !important/);

  assert.match(flow, /elementIsCheckoutVisible/);
  assert.match(flow, /useLayoutEffect/);
  assert.match(flow, /getUsableViewportHeight/);
  assert.match(flow, /getUsableViewportWidth/);
  assert.match(flow, /visibleViewportBounds/);
  assert.match(flow, /floatingDockStyleForCartPanel/);
  assert.match(flow, /getBoundingClientRect\(\)/);
  assert.match(flow, /FLOATING_ACTION_MIN_PANEL_WIDTH/);
  assert.match(flow, /FLOATING_ACTION_MAX_WIDTH/);
  assert.match(flow, /sameFloatingActionStyle/);
  assert.match(flow, /style=\{floatingActionStyle\}/);
  assert.match(flow, /"--pos-checkout-dock-left"/);
  assert.match(flow, /"--pos-checkout-dock-right"/);
  assert.match(flow, /"--pos-checkout-dock-width"/);
  assert.match(flow, /"--pos-checkout-dock-transform"/);
  assert.doesNotMatch(flow, /aria-label="Pinned checkout action"/);
  assert.match(flow, /aria-label="Pinned complete sale action"/);
  assert.match(flow, /completeButtonIsDisabled/);
  assert.match(flow, /button\.click\(\)/);
  assert.match(flowCss, /\.floatingActionDock[\s\S]*position: fixed/);
  assert.match(flowCss, /\.floatingActionDock[\s\S]*bottom: max\(32px, calc\(env\(safe-area-inset-bottom\) \+ 24px\)\)/);
  assert.match(flowCss, /\.floatingActionDock[\s\S]*z-index: 5100/);
  assert.match(flowCss, /\.floatingCompleteButton/);
});
