import { PrismaClient } from "@prisma/client";

const databaseUrl = process.env.DATABASE_URL || "";

if (!databaseUrl.startsWith("file:")) {
  throw new Error("prisma/init-sqlite.ts is dev-only and refuses non-SQLite DATABASE_URL values.");
}

const prisma = new PrismaClient();

const statements = [
  `PRAGMA foreign_keys = ON`,
  `CREATE TABLE IF NOT EXISTS "User" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL UNIQUE,
    "name" TEXT NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'FRIEND',
    "passwordHash" TEXT NOT NULL,
    "canAddSightings" BOOLEAN NOT NULL DEFAULT true,
    "canAddComps" BOOLEAN NOT NULL DEFAULT false,
    "canRunChecks" BOOLEAN NOT NULL DEFAULT false,
    "canReceivePushAlerts" BOOLEAN NOT NULL DEFAULT true,
    "preferredZone" TEXT NOT NULL DEFAULT 'MIAMI',
    "customZoneName" TEXT,
    "hideDistantStores" BOOLEAN NOT NULL DEFAULT false,
    "currentLatitude" REAL,
    "currentLongitude" REAL,
    "locationUpdatedAt" DATETIME,
    "disabledAt" DATETIME,
    "sessionVersion" INTEGER NOT NULL DEFAULT 0,
    "lastLoginAt" DATETIME,
    "passwordChangedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "PasswordResetToken" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL UNIQUE,
    "expiresAt" DATETIME NOT NULL,
    "usedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PasswordResetToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "FriendInvite" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "tokenHash" TEXT NOT NULL UNIQUE,
    "role" TEXT NOT NULL DEFAULT 'FRIEND',
    "canAddSightings" BOOLEAN NOT NULL DEFAULT true,
    "canAddComps" BOOLEAN NOT NULL DEFAULT false,
    "canRunChecks" BOOLEAN NOT NULL DEFAULT false,
    "canReceivePushAlerts" BOOLEAN NOT NULL DEFAULT true,
    "expiresAt" DATETIME NOT NULL,
    "acceptedAt" DATETIME,
    "revokedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdById" TEXT,
    "acceptedById" TEXT,
    CONSTRAINT "FriendInvite_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "FriendInvite_acceptedById_fkey" FOREIGN KEY ("acceptedById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "AuditLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "actorEmail" TEXT,
    "action" TEXT NOT NULL,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT,
    "summary" TEXT NOT NULL,
    "metadata" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Retailer" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL UNIQUE,
    "website" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "Product" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "retailerId" TEXT NOT NULL,
    "releaseId" TEXT,
    "name" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "setName" TEXT,
    "productType" TEXT,
    "imageUrl" TEXT,
    "expectedTitleKeywords" TEXT,
    "sku" TEXT,
    "upc" TEXT,
    "dpci" TEXT,
    "retailerProductId" TEXT,
    "verificationStatus" TEXT NOT NULL DEFAULT 'UNVERIFIED',
    "verifiedAt" DATETIME,
    "verifiedFinalUrl" TEXT,
    "verificationNotes" TEXT,
    "retailPrice" REAL,
    "liveTitle" TEXT,
    "livePrice" REAL,
    "livePriceSource" TEXT,
    "livePriceVerifiedAt" DATETIME,
    "liveStockStatus" TEXT,
    "liveStockVerifiedAt" DATETIME,
    "liveImageUrl" TEXT,
    "liveConfidenceScore" INTEGER,
    "liveBlockedType" TEXT,
    "isDemoData" BOOLEAN NOT NULL DEFAULT false,
    "stockStatus" TEXT NOT NULL DEFAULT 'UNAVAILABLE',
    "alertStatus" BOOLEAN NOT NULL DEFAULT false,
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "rating" TEXT NOT NULL DEFAULT 'WATCH',
    "notes" TEXT,
    "lastCheckedAt" DATETIME,
    "lastSuccessfulCheckedAt" DATETIME,
    "monitorEnabled" BOOLEAN NOT NULL DEFAULT true,
    "checkFrequencyMinutes" INTEGER NOT NULL DEFAULT 60,
    "nextCheckAt" DATETIME,
    "lastMonitorResult" TEXT,
    "lastMonitorError" TEXT,
    "lastPageHash" TEXT,
    "lastAlertSentAt" DATETIME,
    "requiredWords" TEXT,
    "ignoreWords" TEXT,
    "pendingAlertStatus" TEXT,
    "pendingAlertPrice" REAL,
    "pendingAlertPageHash" TEXT,
    "pendingAlertCount" INTEGER NOT NULL DEFAULT 0,
    "pendingAlertReason" TEXT,
    "pendingAlertConfidence" INTEGER,
    "pendingAlertDetectedWords" TEXT,
    "pendingAlertAt" DATETIME,
    "sealedResaleNotes" TEXT,
    "scarcityNotes" TEXT,
    "manualPriorityOverride" TEXT,
    "archivedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Product_retailerId_fkey" FOREIGN KEY ("retailerId") REFERENCES "Retailer" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "Product_releaseId_fkey" FOREIGN KEY ("releaseId") REFERENCES "Release" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Store" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "retailerId" TEXT NOT NULL,
    "storeName" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "zone" TEXT NOT NULL DEFAULT 'MIAMI',
    "latitude" REAL,
    "longitude" REAL,
    "notes" TEXT,
    "typicalRestockDays" TEXT NOT NULL,
    "typicalRestockTimeWindow" TEXT NOT NULL,
    "vendorNotes" TEXT,
    "confidenceScore" INTEGER NOT NULL DEFAULT 50,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Store_retailerId_fkey" FOREIGN KEY ("retailerId") REFERENCES "Retailer" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "UserStorePreference" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "storeId" TEXT NOT NULL,
    "favorite" BOOLEAN NOT NULL DEFAULT false,
    "hidden" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "UserStorePreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "UserStorePreference_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "StoreSighting" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "storeId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "productSeen" TEXT NOT NULL,
    "resultType" TEXT NOT NULL DEFAULT 'stock_seen',
    "seenAt" DATETIME NOT NULL,
    "quantityEstimate" TEXT NOT NULL,
    "shelfPhotoUrl" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StoreSighting_storeId_fkey" FOREIGN KEY ("storeId") REFERENCES "Store" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StoreSighting_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Release" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "setName" TEXT NOT NULL,
    "productType" TEXT,
    "officialReleaseDate" DATETIME NOT NULL,
    "preorderDate" DATETIME,
    "productTypes" TEXT NOT NULL,
    "pokemonCenterExclusiveVersion" BOOLEAN NOT NULL DEFAULT false,
    "chaseCards" TEXT,
    "demandRating" TEXT NOT NULL DEFAULT 'MEDIUM',
    "estimatedDemand" TEXT NOT NULL DEFAULT 'MEDIUM',
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "sealedProductPriority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "notes" TEXT,
    "productLinks" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "Alert" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "title" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "priority" TEXT NOT NULL DEFAULT 'MEDIUM',
    "timestamp" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "entityType" TEXT NOT NULL,
    "entityId" TEXT,
    "actionUrl" TEXT,
    "read" BOOLEAN NOT NULL DEFAULT false,
    "score" INTEGER NOT NULL DEFAULT 50,
    "dedupeKey" TEXT,
    "explanation" TEXT,
    "falsePositiveAt" DATETIME,
    "suppressedAt" DATETIME,
    "cooldownUntil" DATETIME,
    "productId" TEXT,
    "userId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Alert_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "Alert_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "NotificationDeliveryLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "alertId" TEXT,
    "userId" TEXT,
    "productId" TEXT,
    "channel" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "reason" TEXT,
    "detail" TEXT,
    "dedupeKey" TEXT,
    "priority" TEXT,
    "entityType" TEXT,
    "entityId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "RestockHistory" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "productId" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "price" REAL,
    "snapshotReason" TEXT NOT NULL,
    "checkedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "RestockHistory_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "MonitorLog" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "productId" TEXT,
    "runType" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "previousStatus" TEXT,
    "detectedStatus" TEXT,
    "previousPrice" REAL,
    "detectedPrice" REAL,
    "changeSummary" TEXT,
    "httpStatus" INTEGER,
    "finalUrl" TEXT,
    "responseTimeMs" INTEGER,
    "detectedWords" TEXT,
    "confidenceScore" INTEGER,
    "reason" TEXT,
    "blockedType" TEXT,
    "pageHash" TEXT,
    "startedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" DATETIME,
    "durationMs" INTEGER,
    "error" TEXT,
    "alertSent" BOOLEAN NOT NULL DEFAULT false,
    "notificationSummary" TEXT,
    CONSTRAINT "MonitorLog_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ProductDiscoverySource" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "retailerId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "notes" TEXT,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "checkFrequencyMinutes" INTEGER NOT NULL DEFAULT 360,
    "nextCheckAt" DATETIME,
    "lastCheckedAt" DATETIME,
    "lastSuccessfulCheckedAt" DATETIME,
    "lastResult" TEXT,
    "lastError" TEXT,
    "lastFoundCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProductDiscoverySource_retailerId_fkey" FOREIGN KEY ("retailerId") REFERENCES "Retailer" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ProductDiscoveryCandidate" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "sourceId" TEXT NOT NULL,
    "retailerId" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "finalUrl" TEXT,
    "productName" TEXT NOT NULL,
    "productType" TEXT,
    "retailerProductId" TEXT,
    "sku" TEXT,
    "upc" TEXT,
    "dpci" TEXT,
    "brand" TEXT,
    "category" TEXT,
    "description" TEXT,
    "itemDetails" TEXT,
    "imageUrl" TEXT,
    "livePrice" REAL,
    "stockStatus" TEXT,
    "enrichmentStatus" TEXT NOT NULL DEFAULT 'NEEDS_REVIEW',
    "enrichmentReason" TEXT,
    "enrichedAt" DATETIME,
    "confidenceScore" INTEGER NOT NULL DEFAULT 50,
    "reason" TEXT,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "approvedProductId" TEXT,
    "reviewedAt" DATETIME,
    "ignoredAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProductDiscoveryCandidate_sourceId_fkey" FOREIGN KEY ("sourceId") REFERENCES "ProductDiscoverySource" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ProductDiscoveryCandidate_retailerId_fkey" FOREIGN KEY ("retailerId") REFERENCES "Retailer" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Card" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "releaseId" TEXT,
    "cardName" TEXT NOT NULL,
    "setName" TEXT NOT NULL,
    "cardNumber" TEXT NOT NULL,
    "rarity" TEXT NOT NULL,
    "rawAveragePrice" REAL NOT NULL,
    "psa9AverageSalePrice" REAL NOT NULL,
    "psa10AverageSalePrice" REAL NOT NULL,
    "bgs95AverageSalePrice" REAL NOT NULL DEFAULT 0,
    "bgs10AverageSalePrice" REAL NOT NULL DEFAULT 0,
    "bgsBlackLabelAverageSalePrice" REAL NOT NULL DEFAULT 0,
    "estimatedEbayFee" REAL NOT NULL DEFAULT 0.1325,
    "estimatedGradingCost" REAL NOT NULL,
    "estimatedShippingCost" REAL NOT NULL DEFAULT 5,
    "minimumProfitTarget" REAL NOT NULL DEFAULT 20,
    "psa9EstimatedProfit" REAL NOT NULL,
    "psa10EstimatedProfit" REAL NOT NULL,
    "bgs10EstimatedProfit" REAL NOT NULL DEFAULT 0,
    "blackLabelEstimatedProfit" REAL NOT NULL DEFAULT 0,
    "maxRawBuyPricePsa9" REAL NOT NULL,
    "maxRawBuyPrice" REAL NOT NULL DEFAULT 0,
    "top10Score" INTEGER NOT NULL DEFAULT 0,
    "compConfidenceScore" INTEGER NOT NULL DEFAULT 0,
    "rating" TEXT NOT NULL DEFAULT 'WATCH',
    "dataSource" TEXT NOT NULL,
    "lastRefreshed" DATETIME NOT NULL,
    "notes" TEXT,
    "characterName" TEXT,
    "era" TEXT NOT NULL DEFAULT 'MODERN',
    "lowPop" BOOLEAN NOT NULL DEFAULT false,
    "newRelease" BOOLEAN NOT NULL DEFAULT false,
    "lowNumberedSerialized" BOOLEAN NOT NULL DEFAULT false,
    "strongCharacterDemand" BOOLEAN NOT NULL DEFAULT false,
    "ebayIncludeWords" TEXT,
    "ebayExcludeWords" TEXT,
    "ebayExactSetName" BOOLEAN NOT NULL DEFAULT true,
    "ebayCardNumberRequired" BOOLEAN NOT NULL DEFAULT true,
    "ebayRawKeywords" TEXT,
    "ebayPsa9Keywords" TEXT,
    "ebayPsa10Keywords" TEXT,
    "ebayAllowNonEnglish" BOOLEAN NOT NULL DEFAULT false,
    "lastCompAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Card_releaseId_fkey" FOREIGN KEY ("releaseId") REFERENCES "Release" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CardPriceSnapshot" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "cardId" TEXT NOT NULL,
    "rawAveragePrice" REAL NOT NULL,
    "psa9AverageSalePrice" REAL NOT NULL,
    "psa10AverageSalePrice" REAL NOT NULL,
    "bgs95AverageSalePrice" REAL NOT NULL DEFAULT 0,
    "bgs10AverageSalePrice" REAL NOT NULL DEFAULT 0,
    "bgsBlackLabelAverageSalePrice" REAL NOT NULL DEFAULT 0,
    "psa9EstimatedProfit" REAL NOT NULL,
    "psa10EstimatedProfit" REAL NOT NULL,
    "bgs10EstimatedProfit" REAL NOT NULL DEFAULT 0,
    "blackLabelEstimatedProfit" REAL NOT NULL DEFAULT 0,
    "maxRawBuyPrice" REAL NOT NULL DEFAULT 0,
    "top10Score" INTEGER NOT NULL DEFAULT 0,
    "rating" TEXT NOT NULL,
    "snapshotAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CardPriceSnapshot_cardId_fkey" FOREIGN KEY ("cardId") REFERENCES "Card" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CardCompSale" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "cardId" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "salePrice" REAL NOT NULL,
    "grade" TEXT NOT NULL,
    "gradeType" TEXT NOT NULL DEFAULT 'RAW',
    "soldAt" DATETIME NOT NULL,
    "url" TEXT,
    "sourceUrl" TEXT,
    "saleTitle" TEXT,
    "matchScore" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "conditionNotes" TEXT,
    "sourceQuality" TEXT NOT NULL DEFAULT 'EBAY_SOLD',
    "reviewStatus" TEXT NOT NULL DEFAULT 'ACCEPTED',
    "rejectedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CardCompSale_cardId_fkey" FOREIGN KEY ("cardId") REFERENCES "Card" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "InvestmentReport" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "title" TEXT NOT NULL,
    "generatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "periodStart" DATETIME NOT NULL,
    "periodEnd" DATETIME NOT NULL,
    "top10RawToGrade" TEXT NOT NULL,
    "safestPsa9Flips" TEXT NOT NULL,
    "highestPsa10Upside" TEXT NOT NULL,
    "beckettCandidates" TEXT NOT NULL,
    "avoidOverpriced" TEXT NOT NULL,
    "bestBuy" TEXT,
    "riskiestBuy" TEXT,
    "bestUnder25Raw" TEXT,
    "bestPremiumCard" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "InvestmentReport_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "InvestmentSettings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL UNIQUE,
    "gradingCost" REAL NOT NULL DEFAULT 20,
    "ebaySellingFee" REAL NOT NULL DEFAULT 0.1325,
    "shippingCost" REAL NOT NULL DEFAULT 5,
    "minimumProfitTarget" REAL NOT NULL DEFAULT 20,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "InvestmentSettings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "InventoryItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "itemType" TEXT NOT NULL,
    "itemName" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'sealed_packs',
    "setName" TEXT,
    "productId" TEXT,
    "cardId" TEXT,
    "cost" REAL NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "totalCost" REAL,
    "purchaseExtraCost" REAL,
    "source" TEXT NOT NULL,
    "retailer" TEXT,
    "brand" TEXT,
    "description" TEXT,
    "manufacturer" TEXT,
    "model" TEXT,
    "msrp" REAL,
    "purchasedAt" DATETIME NOT NULL,
    "receiptNumber" TEXT,
    "receiptImageUrl" TEXT,
    "orderNumber" TEXT,
    "transactionId" TEXT,
    "sourceStore" TEXT,
    "paymentMethod" TEXT,
    "exactProductUrl" TEXT,
    "upc" TEXT,
    "sku" TEXT,
    "dpci" TEXT,
    "asin" TEXT,
    "imageUrl" TEXT,
    "condition" TEXT,
    "itemStatus" TEXT NOT NULL DEFAULT 'sealed',
    "targetSellPrice" REAL,
    "minimumAcceptablePrice" REAL,
    "listingPlatform" TEXT,
    "listingStatus" TEXT NOT NULL DEFAULT 'not_listed',
    "soldPrice" REAL,
    "soldAt" DATETIME,
    "buyerPlatform" TEXT,
    "currentMarketEstimate" REAL,
    "marketAverageSalePrice" REAL,
    "marketCompCount" INTEGER NOT NULL DEFAULT 0,
    "marketLastRefreshedAt" DATETIME,
    "marketConfidence" TEXT NOT NULL DEFAULT 'LOW',
    "estimatedEbayFee" REAL,
    "estimatedShippingCost" REAL,
    "estimatedNetProfit" REAL,
    "roiPercent" REAL,
    "recommendedAction" TEXT NOT NULL DEFAULT 'HOLD',
    "recommendationReason" TEXT,
    "netProfitAfterFees" REAL,
    "publishToStore" BOOLEAN NOT NULL DEFAULT false,
    "publicSlug" TEXT,
    "publicTitle" TEXT,
    "publicDescription" TEXT,
    "publicPrice" REAL,
    "compareAtPrice" REAL,
    "publicImages" TEXT,
    "availableForSale" INTEGER,
    "maxQuantityPerOrder" INTEGER NOT NULL DEFAULT 4,
    "purchaseLimitEnabled" BOOLEAN NOT NULL DEFAULT false,
    "shippingProfile" TEXT NOT NULL DEFAULT 'standard',
    "packageWeightOz" REAL,
    "packageLengthIn" REAL,
    "packageWidthIn" REAL,
    "packageHeightIn" REAL,
    "shippingMetadataSource" TEXT,
    "freeShippingEligible" BOOLEAN NOT NULL DEFAULT false,
    "requiresBox" BOOLEAN NOT NULL DEFAULT false,
    "insuranceRecommended" BOOLEAN NOT NULL DEFAULT false,
    "storeStatus" TEXT NOT NULL DEFAULT 'draft',
    "localPickupAvailable" BOOLEAN NOT NULL DEFAULT true,
    "shippingAvailable" BOOLEAN NOT NULL DEFAULT true,
    "storefrontCategory" TEXT,
    "storefrontTags" TEXT,
    "expectedPlan" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "InventoryItem_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "InventoryItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "InventoryItem_cardId_fkey" FOREIGN KEY ("cardId") REFERENCES "Card" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "InventoryProductImage" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "inventoryItemId" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "altText" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isPrimary" BOOLEAN NOT NULL DEFAULT false,
    "source" TEXT NOT NULL DEFAULT 'manual',
    "showInStore" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "InventoryProductImage_inventoryItemId_fkey" FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "InventoryStockLot" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "inventoryItemId" TEXT NOT NULL,
    "purchasedAt" DATETIME NOT NULL,
    "source" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "costPerUnit" REAL NOT NULL,
    "purchaseExtraCost" REAL,
    "totalCost" REAL NOT NULL,
    "remainingQuantity" INTEGER NOT NULL,
    "notes" TEXT,
    "receiptNumber" TEXT,
    "receiptImageUrl" TEXT,
    "orderNumber" TEXT,
    "transactionId" TEXT,
    "sourceStore" TEXT,
    "paymentMethod" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "InventoryStockLot_inventoryItemId_fkey" FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "InventorySale" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "inventoryItemId" TEXT NOT NULL,
    "userId" TEXT,
    "quantitySold" INTEGER NOT NULL,
    "soldPricePerItem" REAL NOT NULL,
    "grossSale" REAL NOT NULL,
    "platform" TEXT NOT NULL,
    "fees" REAL NOT NULL DEFAULT 0,
    "shippingCost" REAL NOT NULL DEFAULT 0,
    "netSale" REAL NOT NULL,
    "costBasis" REAL NOT NULL,
    "profitLoss" REAL NOT NULL,
    "roiPercent" REAL,
    "soldAt" DATETIME NOT NULL,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "InventorySale_inventoryItemId_fkey" FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "InventorySale_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "InventoryMarketComp" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "inventoryItemId" TEXT NOT NULL,
    "saleTitle" TEXT NOT NULL,
    "salePrice" REAL NOT NULL,
    "soldAt" DATETIME NOT NULL,
    "sourceUrl" TEXT,
    "sourceQuality" TEXT NOT NULL DEFAULT 'EBAY_SOLD',
    "matchScore" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "InventoryMarketComp_inventoryItemId_fkey" FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "BarcodeScan" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "upc" TEXT NOT NULL,
    "rawCode" TEXT,
    "normalizedUpc" TEXT,
    "variantsChecked" TEXT,
    "source" TEXT NOT NULL DEFAULT 'manual',
    "status" TEXT NOT NULL DEFAULT 'LOOKUP_FAILED',
    "resultType" TEXT NOT NULL DEFAULT 'manual',
    "productId" TEXT,
    "inventoryItemId" TEXT,
    "productName" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BarcodeScan_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "BarcodeScan_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "BarcodeScan_inventoryItemId_fkey" FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "StorefrontSettings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL UNIQUE,
    "storeName" TEXT NOT NULL DEFAULT 'GameDayGrabs LLC',
    "storeLogoUrl" TEXT,
    "sportsCardsExternalUrl" TEXT,
    "contactEmail" TEXT,
    "returnPolicyText" TEXT,
    "shippingPolicyText" TEXT,
    "localPickupInstructions" TEXT,
    "announcementBanner" TEXT,
    "defaultShippingPrice" REAL NOT NULL DEFAULT 5,
    "freeShippingThreshold" REAL,
    "socialLinks" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StorefrontSettings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `ALTER TABLE "StorefrontSettings" ADD COLUMN "sportsCardsExternalUrl" TEXT`,
  `CREATE TABLE IF NOT EXISTS "StorefrontCustomer" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "customerAccountId" TEXT,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "phone" TEXT,
    "stripeCustomerId" TEXT,
    "firstOrderAt" DATETIME,
    "lastOrderAt" DATETIME,
    "totalOrders" INTEGER NOT NULL DEFAULT 0,
    "totalSpent" REAL NOT NULL DEFAULT 0,
    "defaultShippingName" TEXT,
    "defaultShippingLine1" TEXT,
    "defaultShippingLine2" TEXT,
    "defaultShippingCity" TEXT,
    "defaultShippingState" TEXT,
    "defaultShippingPostalCode" TEXT,
    "defaultShippingCountry" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StorefrontCustomer_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CustomerAccount" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "email" TEXT NOT NULL,
    "normalizedEmail" TEXT,
    "displayName" TEXT,
    "phone" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "passwordHash" TEXT,
    "passwordSetAt" DATETIME,
    "sessionRevokedBefore" DATETIME,
    "emailVerifiedAt" DATETIME,
    "lastLoginAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CustomerAccount_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CustomerSession" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "customerAccountId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL UNIQUE,
    "lastActivityAt" DATETIME NOT NULL,
    "absoluteExpiresAt" DATETIME NOT NULL,
    "revokedAt" DATETIME,
    "revokeReason" TEXT,
    "userAgentSummary" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CustomerSession_customerAccountId_fkey" FOREIGN KEY ("customerAccountId") REFERENCES "CustomerAccount" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CustomerAuthRateLimit" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "action" TEXT NOT NULL,
    "emailKeyHash" TEXT NOT NULL,
    "clientKeyHash" TEXT NOT NULL,
    "windowStart" DATETIME NOT NULL,
    "windowSeconds" INTEGER NOT NULL,
    "attemptCount" INTEGER NOT NULL DEFAULT 0,
    "firstAttemptAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastAttemptAt" DATETIME NOT NULL,
    "blockedUntil" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS "CustomerSavedAddress" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "customerAccountId" TEXT NOT NULL,
    "name" TEXT,
    "street1" TEXT NOT NULL,
    "street2" TEXT,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "zip" TEXT NOT NULL,
    "country" TEXT NOT NULL DEFAULT 'US',
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CustomerSavedAddress_customerAccountId_fkey" FOREIGN KEY ("customerAccountId") REFERENCES "CustomerAccount" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CustomerMagicLinkToken" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "customerAccountId" TEXT,
    "email" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL UNIQUE,
    "expiresAt" DATETIME NOT NULL,
    "usedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CustomerMagicLinkToken_customerAccountId_fkey" FOREIGN KEY ("customerAccountId") REFERENCES "CustomerAccount" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "CustomerPasswordResetToken" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "customerAccountId" TEXT NOT NULL,
    "tokenHash" TEXT NOT NULL UNIQUE,
    "expiresAt" DATETIME NOT NULL,
    "usedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CustomerPasswordResetToken_customerAccountId_fkey" FOREIGN KEY ("customerAccountId") REFERENCES "CustomerAccount" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "StorefrontOrder" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "orderNumber" TEXT NOT NULL UNIQUE,
    "userId" TEXT,
    "customerId" TEXT,
    "customerAccountId" TEXT,
    "customerEmail" TEXT,
    "customerName" TEXT,
    "customerPhone" TEXT,
    "shippingName" TEXT,
    "shippingLine1" TEXT,
    "shippingLine2" TEXT,
    "shippingCity" TEXT,
    "shippingState" TEXT,
    "shippingPostalCode" TEXT,
    "shippingCountry" TEXT,
    "billingName" TEXT,
    "billingLine1" TEXT,
    "billingLine2" TEXT,
    "billingCity" TEXT,
    "billingState" TEXT,
    "billingPostalCode" TEXT,
    "billingCountry" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending_payment',
    "paymentStatus" TEXT NOT NULL DEFAULT 'pending',
    "fulfillmentStatus" TEXT NOT NULL DEFAULT 'unfulfilled',
    "stripeCheckoutSessionId" TEXT UNIQUE,
    "stripePaymentIntentId" TEXT,
    "subtotal" REAL NOT NULL DEFAULT 0,
    "shippingCharged" REAL NOT NULL DEFAULT 0,
    "shippingMethodLabel" TEXT,
    "shippingRateSource" TEXT,
    "shippingPackageWeightOz" REAL,
    "shippingPackageLengthIn" REAL,
    "shippingPackageWidthIn" REAL,
    "shippingPackageHeightIn" REAL,
    "shippingPackageProfile" TEXT,
    "shippingWarnings" TEXT,
    "shippingQuoteId" TEXT,
    "shippingQuoteProvider" TEXT,
    "shippingCarrier" TEXT,
    "shippingService" TEXT,
    "shippingQuotedAmountCents" INTEGER,
    "shippingQuotedZip" TEXT,
    "shippingQuoteFallbackUsed" BOOLEAN NOT NULL DEFAULT false,
    "shippingQuoteRateProviderRef" TEXT,
    "shippingQuoteShipmentProviderRef" TEXT,
    "shippingQuoteExpiresAt" DATETIME,
    "shippingZipMismatchReview" BOOLEAN NOT NULL DEFAULT false,
    "shippingLabelProvider" TEXT,
    "shippingLabelProviderId" TEXT,
    "shippingLabelUrl" TEXT,
    "shippingLabelFileType" TEXT,
    "shippingTrackingNumber" TEXT,
    "shippingTrackingUrl" TEXT,
    "shippingLabelCostCents" INTEGER,
    "shippingLabelCurrency" TEXT,
    "shippingLabelPurchasedAt" DATETIME,
    "shippingLabelVoidedAt" DATETIME,
    "shippingLabelStatus" TEXT,
    "tax" REAL NOT NULL DEFAULT 0,
    "total" REAL NOT NULL DEFAULT 0,
    "stripeFeeEstimate" REAL NOT NULL DEFAULT 0,
    "shippingCost" REAL NOT NULL DEFAULT 0,
    "costBasis" REAL NOT NULL DEFAULT 0,
    "netProfit" REAL NOT NULL DEFAULT 0,
    "roiPercent" REAL,
    "trackingNumber" TEXT,
    "carrier" TEXT,
    "notes" TEXT,
    "paidAt" DATETIME,
    "canceledAt" DATETIME,
    "refundedAt" DATETIME,
    "refundStatus" TEXT,
    "refundedAmount" REAL NOT NULL DEFAULT 0,
    "refundCurrency" TEXT NOT NULL DEFAULT 'usd',
    "stripeRefundId" TEXT,
    "refundReason" TEXT,
    "refundNote" TEXT,
    "stockReturnStatus" TEXT,
    "stockReturnedAt" DATETIME,
    "customerCancellationEmailStatus" TEXT,
    "customerCancellationEmailSentAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StorefrontOrder_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "StorefrontOrder_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "StorefrontCustomer" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ShippingQuote" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "quoteToken" TEXT NOT NULL UNIQUE,
    "userId" TEXT,
    "orderId" TEXT,
    "provider" TEXT NOT NULL,
    "carrier" TEXT NOT NULL,
    "service" TEXT NOT NULL,
    "amountCents" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "destinationZip" TEXT NOT NULL,
    "country" TEXT NOT NULL DEFAULT 'US',
    "packageWeightOz" REAL,
    "packageLengthIn" REAL,
    "packageWidthIn" REAL,
    "packageHeightIn" REAL,
    "packageProfileKey" TEXT,
    "rateProviderRef" TEXT,
    "shipmentProviderRef" TEXT,
    "fallbackUsed" BOOLEAN NOT NULL DEFAULT false,
    "warning" TEXT,
    "expiresAt" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "usedAt" DATETIME,
    "cartHash" TEXT,
    CONSTRAINT "ShippingQuote_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ShippingQuote_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "StorefrontOrder" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "StorefrontOrderItem" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "orderId" TEXT NOT NULL,
    "inventoryItemId" TEXT NOT NULL,
    "publicTitle" TEXT NOT NULL,
    "publicSlug" TEXT,
    "imageUrl" TEXT,
    "quantity" INTEGER NOT NULL,
    "unitPrice" REAL NOT NULL,
    "lineTotal" REAL NOT NULL,
    "costBasis" REAL NOT NULL DEFAULT 0,
    "profitLoss" REAL NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "StorefrontOrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "StorefrontOrder" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StorefrontOrderItem_inventoryItemId_fkey" FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "StockReservation" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "inventoryItemId" TEXT NOT NULL,
    "orderId" TEXT,
    "stripeCheckoutSessionId" TEXT,
    "quantity" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'reserved',
    "expiresAt" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "releasedAt" DATETIME,
    CONSTRAINT "StockReservation_inventoryItemId_fkey" FOREIGN KEY ("inventoryItemId") REFERENCES "InventoryItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "StockReservation_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "StorefrontOrder" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "PaymentEvent" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "orderId" TEXT,
    "provider" TEXT NOT NULL DEFAULT 'stripe',
    "eventId" TEXT NOT NULL UNIQUE,
    "eventType" TEXT NOT NULL,
    "payload" TEXT,
    "receivedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PaymentEvent_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "StorefrontOrder" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "RewardLedgerEntry" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "customerAccountId" TEXT NOT NULL,
    "orderId" TEXT,
    "points" INTEGER NOT NULL,
    "type" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "idempotencyKey" TEXT,
    "metadataJson" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "RewardLedgerEntry_customerAccountId_fkey" FOREIGN KEY ("customerAccountId") REFERENCES "CustomerAccount" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "RewardLedgerEntry_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "StorefrontOrder" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "RewardBalance" (
    "customerAccountId" TEXT NOT NULL PRIMARY KEY,
    "availablePoints" INTEGER NOT NULL DEFAULT 0,
    "lifetimeEarnedPoints" INTEGER NOT NULL DEFAULT 0,
    "pendingPoints" INTEGER NOT NULL DEFAULT 0,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "RewardBalance_customerAccountId_fkey" FOREIGN KEY ("customerAccountId") REFERENCES "CustomerAccount" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "Fulfillment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "orderId" TEXT NOT NULL UNIQUE,
    "status" TEXT NOT NULL DEFAULT 'unfulfilled',
    "carrier" TEXT,
    "trackingNumber" TEXT,
    "shippedAt" DATETIME,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Fulfillment_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "StorefrontOrder" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "DailyRecap" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT,
    "recapDate" DATETIME NOT NULL,
    "summary" TEXT NOT NULL,
    "productChecks" INTEGER NOT NULL DEFAULT 0,
    "storeVisits" INTEGER NOT NULL DEFAULT 0,
    "purchases" INTEGER NOT NULL DEFAULT 0,
    "alertsCreated" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "DailyRecap_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "SavedFilterPreset" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "section" TEXT NOT NULL,
    "filters" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SavedFilterPreset_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "ProductPriorityScore" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "productId" TEXT NOT NULL,
    "releaseId" TEXT,
    "buyWatchSkip" TEXT NOT NULL,
    "score" INTEGER NOT NULL,
    "retailPriceScore" INTEGER NOT NULL DEFAULT 0,
    "resaleDemandScore" INTEGER NOT NULL DEFAULT 0,
    "setPopularityScore" INTEGER NOT NULL DEFAULT 0,
    "scarcityScore" INTEGER NOT NULL DEFAULT 0,
    "chaseCardScore" INTEGER NOT NULL DEFAULT 0,
    "sealedValueScore" INTEGER NOT NULL DEFAULT 0,
    "cardInvestmentScore" INTEGER NOT NULL DEFAULT 0,
    "profitablePsa9Count" INTEGER NOT NULL DEFAULT 0,
    "psa10Upside" REAL NOT NULL DEFAULT 0,
    "manualOverride" TEXT,
    "reason" TEXT,
    "userNotes" TEXT,
    "computedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ProductPriorityScore_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "NotificationSettings" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL UNIQUE,
    "inApp" BOOLEAN NOT NULL DEFAULT true,
    "sms" BOOLEAN NOT NULL DEFAULT false,
    "email" BOOLEAN NOT NULL DEFAULT false,
    "browserPush" BOOLEAN NOT NULL DEFAULT false,
    "phone" TEXT,
    "emailTo" TEXT,
    "quietHoursStart" TEXT,
    "quietHoursEnd" TEXT,
    "minimumPriority" TEXT NOT NULL DEFAULT 'LOW',
    "alertDigestMode" BOOLEAN NOT NULL DEFAULT false,
    "urgentOnlyMode" BOOLEAN NOT NULL DEFAULT false,
    "highPriorityOverride" BOOLEAN NOT NULL DEFAULT true,
    "watchedRetailers" TEXT,
    "watchedProducts" TEXT,
    "alertCooldownMinutes" INTEGER NOT NULL DEFAULT 30,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "NotificationSettings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS "BrowserPushSubscription" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "endpoint" TEXT NOT NULL UNIQUE,
    "p256dh" TEXT NOT NULL,
    "auth" TEXT NOT NULL,
    "userAgent" TEXT,
    "disabledAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BrowserPushSubscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
  )`,
  `ALTER TABLE "Product" ADD COLUMN "monitorEnabled" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "User" ADD COLUMN "canAddSightings" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "User" ADD COLUMN "canAddComps" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "User" ADD COLUMN "canRunChecks" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "User" ADD COLUMN "canReceivePushAlerts" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "User" ADD COLUMN "preferredZone" TEXT NOT NULL DEFAULT 'MIAMI'`,
  `ALTER TABLE "User" ADD COLUMN "customZoneName" TEXT`,
  `ALTER TABLE "User" ADD COLUMN "hideDistantStores" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "User" ADD COLUMN "currentLatitude" REAL`,
  `ALTER TABLE "User" ADD COLUMN "currentLongitude" REAL`,
  `ALTER TABLE "User" ADD COLUMN "locationUpdatedAt" DATETIME`,
  `ALTER TABLE "User" ADD COLUMN "disabledAt" DATETIME`,
  `ALTER TABLE "User" ADD COLUMN "sessionVersion" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "User" ADD COLUMN "lastLoginAt" DATETIME`,
  `ALTER TABLE "User" ADD COLUMN "passwordChangedAt" DATETIME`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "refundStatus" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "refundedAmount" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "refundCurrency" TEXT NOT NULL DEFAULT 'usd'`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "stripeRefundId" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "refundReason" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "refundNote" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "stockReturnStatus" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "stockReturnedAt" DATETIME`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "customerCancellationEmailStatus" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "customerCancellationEmailSentAt" DATETIME`,
  `ALTER TABLE "Product" ADD COLUMN "lastSuccessfulCheckedAt" DATETIME`,
  `ALTER TABLE "Product" ADD COLUMN "checkFrequencyMinutes" INTEGER NOT NULL DEFAULT 60`,
  `ALTER TABLE "Product" ADD COLUMN "nextCheckAt" DATETIME`,
  `ALTER TABLE "Product" ADD COLUMN "lastMonitorResult" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "lastMonitorError" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "lastPageHash" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "lastAlertSentAt" DATETIME`,
  `ALTER TABLE "Product" ADD COLUMN "requiredWords" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "ignoreWords" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "pendingAlertStatus" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "pendingAlertPrice" REAL`,
  `ALTER TABLE "Product" ADD COLUMN "pendingAlertPageHash" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "pendingAlertCount" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "Product" ADD COLUMN "pendingAlertReason" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "pendingAlertConfidence" INTEGER`,
  `ALTER TABLE "Product" ADD COLUMN "pendingAlertDetectedWords" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "pendingAlertAt" DATETIME`,
  `ALTER TABLE "Product" ADD COLUMN "releaseId" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "setName" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "productType" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "imageUrl" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "expectedTitleKeywords" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "retailerProductId" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "verificationStatus" TEXT NOT NULL DEFAULT 'UNVERIFIED'`,
  `ALTER TABLE "Product" ADD COLUMN "verifiedAt" DATETIME`,
  `ALTER TABLE "Product" ADD COLUMN "verifiedFinalUrl" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "verificationNotes" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "liveTitle" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "livePrice" REAL`,
  `ALTER TABLE "Product" ADD COLUMN "livePriceSource" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "livePriceVerifiedAt" DATETIME`,
  `ALTER TABLE "Product" ADD COLUMN "liveStockStatus" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "liveStockVerifiedAt" DATETIME`,
  `ALTER TABLE "Product" ADD COLUMN "liveImageUrl" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "liveConfidenceScore" INTEGER`,
  `ALTER TABLE "Product" ADD COLUMN "liveBlockedType" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "sellerName" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "sellerType" TEXT NOT NULL DEFAULT 'unknown'`,
  `ALTER TABLE "Product" ADD COLUMN "fulfillmentType" TEXT NOT NULL DEFAULT 'unknown'`,
  `ALTER TABLE "Product" ADD COLUMN "sellerVerified" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "Product" ADD COLUMN "priceStatus" TEXT NOT NULL DEFAULT 'unknown'`,
  `ALTER TABLE "Product" ADD COLUMN "alertEligibility" TEXT NOT NULL DEFAULT 'needs_review'`,
  `ALTER TABLE "Product" ADD COLUMN "expectedRetailPrice" REAL`,
  `ALTER TABLE "Product" ADD COLUMN "maxAlertPrice" REAL`,
  `ALTER TABLE "Product" ADD COLUMN "allowOverMsrp" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "Product" ADD COLUMN "targetRetailMin" REAL`,
  `ALTER TABLE "Product" ADD COLUMN "targetRetailMax" REAL`,
  `ALTER TABLE "Product" ADD COLUMN "targetRetailReason" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "isDemoData" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "Product" ADD COLUMN "sealedResaleNotes" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "scarcityNotes" TEXT`,
  `ALTER TABLE "Product" ADD COLUMN "manualPriorityOverride" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "sku" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "upc" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "dpci" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "brand" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "category" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "description" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "itemDetails" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "enrichmentStatus" TEXT NOT NULL DEFAULT 'NEEDS_REVIEW'`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "enrichmentReason" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "enrichedAt" DATETIME`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "sellerName" TEXT`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "sellerType" TEXT NOT NULL DEFAULT 'unknown'`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "fulfillmentType" TEXT NOT NULL DEFAULT 'unknown'`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "sellerVerified" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "priceStatus" TEXT NOT NULL DEFAULT 'unknown'`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "alertEligibility" TEXT NOT NULL DEFAULT 'needs_review'`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "expectedRetailPrice" REAL`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "maxAlertPrice" REAL`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "targetRetailMin" REAL`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "targetRetailMax" REAL`,
  `ALTER TABLE "ProductDiscoveryCandidate" ADD COLUMN "targetRetailReason" TEXT`,
  `ALTER TABLE "Store" ADD COLUMN "zone" TEXT NOT NULL DEFAULT 'MIAMI'`,
  `ALTER TABLE "Store" ADD COLUMN "latitude" REAL`,
  `ALTER TABLE "Store" ADD COLUMN "longitude" REAL`,
  `ALTER TABLE "StoreSighting" ADD COLUMN "resultType" TEXT NOT NULL DEFAULT 'stock_seen'`,
  `ALTER TABLE "Release" ADD COLUMN "productType" TEXT`,
  `ALTER TABLE "Release" ADD COLUMN "estimatedDemand" TEXT NOT NULL DEFAULT 'MEDIUM'`,
  `ALTER TABLE "Release" ADD COLUMN "sealedProductPriority" TEXT NOT NULL DEFAULT 'MEDIUM'`,
  `ALTER TABLE "Alert" ADD COLUMN "userId" TEXT`,
  `ALTER TABLE "Alert" ADD COLUMN "score" INTEGER NOT NULL DEFAULT 50`,
  `ALTER TABLE "Alert" ADD COLUMN "dedupeKey" TEXT`,
  `ALTER TABLE "Alert" ADD COLUMN "explanation" TEXT`,
  `ALTER TABLE "Alert" ADD COLUMN "falsePositiveAt" DATETIME`,
  `ALTER TABLE "Alert" ADD COLUMN "suppressedAt" DATETIME`,
  `ALTER TABLE "Alert" ADD COLUMN "cooldownUntil" DATETIME`,
  `ALTER TABLE "NotificationSettings" ADD COLUMN "quietHoursStart" TEXT`,
  `ALTER TABLE "NotificationSettings" ADD COLUMN "quietHoursEnd" TEXT`,
  `ALTER TABLE "NotificationSettings" ADD COLUMN "minimumPriority" TEXT NOT NULL DEFAULT 'LOW'`,
  `ALTER TABLE "NotificationSettings" ADD COLUMN "alertDigestMode" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "NotificationSettings" ADD COLUMN "urgentOnlyMode" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "NotificationSettings" ADD COLUMN "highPriorityOverride" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "NotificationSettings" ADD COLUMN "watchedRetailers" TEXT`,
  `ALTER TABLE "NotificationSettings" ADD COLUMN "watchedProducts" TEXT`,
  `ALTER TABLE "NotificationSettings" ADD COLUMN "alertCooldownMinutes" INTEGER NOT NULL DEFAULT 30`,
  `ALTER TABLE "Card" ADD COLUMN "bgs95AverageSalePrice" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "Card" ADD COLUMN "bgs10AverageSalePrice" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "Card" ADD COLUMN "bgsBlackLabelAverageSalePrice" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "Card" ADD COLUMN "estimatedShippingCost" REAL NOT NULL DEFAULT 5`,
  `ALTER TABLE "Card" ADD COLUMN "minimumProfitTarget" REAL NOT NULL DEFAULT 20`,
  `ALTER TABLE "Card" ADD COLUMN "bgs10EstimatedProfit" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "Card" ADD COLUMN "blackLabelEstimatedProfit" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "Card" ADD COLUMN "maxRawBuyPrice" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "Card" ADD COLUMN "top10Score" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "Card" ADD COLUMN "compConfidenceScore" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "Card" ADD COLUMN "characterName" TEXT`,
  `ALTER TABLE "Card" ADD COLUMN "era" TEXT NOT NULL DEFAULT 'MODERN'`,
  `ALTER TABLE "Card" ADD COLUMN "lowNumberedSerialized" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "Card" ADD COLUMN "strongCharacterDemand" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "Card" ADD COLUMN "ebayIncludeWords" TEXT`,
  `ALTER TABLE "Card" ADD COLUMN "ebayExcludeWords" TEXT`,
  `ALTER TABLE "Card" ADD COLUMN "ebayExactSetName" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "Card" ADD COLUMN "ebayCardNumberRequired" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "Card" ADD COLUMN "ebayRawKeywords" TEXT`,
  `ALTER TABLE "Card" ADD COLUMN "ebayPsa9Keywords" TEXT`,
  `ALTER TABLE "Card" ADD COLUMN "ebayPsa10Keywords" TEXT`,
  `ALTER TABLE "Card" ADD COLUMN "ebayAllowNonEnglish" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "Card" ADD COLUMN "lastCompAt" DATETIME`,
  `ALTER TABLE "Card" ADD COLUMN "releaseId" TEXT`,
  `ALTER TABLE "CardPriceSnapshot" ADD COLUMN "bgs95AverageSalePrice" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "CardPriceSnapshot" ADD COLUMN "bgs10AverageSalePrice" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "CardPriceSnapshot" ADD COLUMN "bgsBlackLabelAverageSalePrice" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "CardPriceSnapshot" ADD COLUMN "bgs10EstimatedProfit" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "CardPriceSnapshot" ADD COLUMN "blackLabelEstimatedProfit" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "CardPriceSnapshot" ADD COLUMN "maxRawBuyPrice" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "CardPriceSnapshot" ADD COLUMN "top10Score" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "CardCompSale" ADD COLUMN "gradeType" TEXT NOT NULL DEFAULT 'RAW'`,
  `ALTER TABLE "CardCompSale" ADD COLUMN "sourceUrl" TEXT`,
  `ALTER TABLE "CardCompSale" ADD COLUMN "saleTitle" TEXT`,
  `ALTER TABLE "CardCompSale" ADD COLUMN "matchScore" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "CardCompSale" ADD COLUMN "conditionNotes" TEXT`,
  `ALTER TABLE "CardCompSale" ADD COLUMN "sourceQuality" TEXT NOT NULL DEFAULT 'EBAY_SOLD'`,
  `ALTER TABLE "CardCompSale" ADD COLUMN "reviewStatus" TEXT NOT NULL DEFAULT 'ACCEPTED'`,
  `ALTER TABLE "CardCompSale" ADD COLUMN "rejectedAt" DATETIME`,
  `ALTER TABLE "ProductPriorityScore" ADD COLUMN "releaseId" TEXT`,
  `ALTER TABLE "ProductPriorityScore" ADD COLUMN "profitablePsa9Count" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "ProductPriorityScore" ADD COLUMN "psa10Upside" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "ProductPriorityScore" ADD COLUMN "manualOverride" TEXT`,
  `ALTER TABLE "ProductPriorityScore" ADD COLUMN "reason" TEXT`,
  `ALTER TABLE "MonitorLog" ADD COLUMN "finalUrl" TEXT`,
  `ALTER TABLE "MonitorLog" ADD COLUMN "responseTimeMs" INTEGER`,
  `ALTER TABLE "MonitorLog" ADD COLUMN "detectedWords" TEXT`,
  `ALTER TABLE "MonitorLog" ADD COLUMN "confidenceScore" INTEGER`,
  `ALTER TABLE "MonitorLog" ADD COLUMN "reason" TEXT`,
  `ALTER TABLE "MonitorLog" ADD COLUMN "blockedType" TEXT`,
  `ALTER TABLE "ProductDiscoverySource" ADD COLUMN "lastSuccessfulCheckedAt" DATETIME`,
  `ALTER TABLE "Product" ADD COLUMN "archivedAt" DATETIME`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "category" TEXT NOT NULL DEFAULT 'sealed_packs'`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "setName" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "totalCost" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "purchaseExtraCost" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "retailer" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "brand" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "description" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "manufacturer" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "model" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "msrp" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "receiptNumber" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "receiptImageUrl" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "orderNumber" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "transactionId" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "sourceStore" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "paymentMethod" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "exactProductUrl" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "upc" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "sku" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "dpci" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "asin" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "imageUrl" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "condition" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "itemStatus" TEXT NOT NULL DEFAULT 'sealed'`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "targetSellPrice" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "minimumAcceptablePrice" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "listingPlatform" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "listingStatus" TEXT NOT NULL DEFAULT 'not_listed'`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "soldPrice" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "soldAt" DATETIME`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "buyerPlatform" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "currentMarketEstimate" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "marketAverageSalePrice" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "marketCompCount" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "marketLastRefreshedAt" DATETIME`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "marketConfidence" TEXT NOT NULL DEFAULT 'LOW'`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "estimatedEbayFee" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "estimatedShippingCost" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "estimatedNetProfit" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "roiPercent" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "recommendedAction" TEXT NOT NULL DEFAULT 'HOLD'`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "recommendationReason" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "netProfitAfterFees" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "publishToStore" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "publicSlug" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "publicTitle" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "publicDescription" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "publicPrice" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "compareAtPrice" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "publicImages" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "availableForSale" INTEGER`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "maxQuantityPerOrder" INTEGER NOT NULL DEFAULT 4`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "purchaseLimitEnabled" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "shippingProfile" TEXT NOT NULL DEFAULT 'standard'`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "packageWeightOz" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "packageLengthIn" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "packageWidthIn" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "packageHeightIn" REAL`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "shippingMetadataSource" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "freeShippingEligible" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "requiresBox" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "insuranceRecommended" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "storeStatus" TEXT NOT NULL DEFAULT 'draft'`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "localPickupAvailable" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "shippingAvailable" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "storefrontCategory" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "storefrontTags" TEXT`,
  `ALTER TABLE "InventoryItem" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP`,
  `ALTER TABLE "InventoryStockLot" ADD COLUMN "receiptImageUrl" TEXT`,
  `ALTER TABLE "InventoryStockLot" ADD COLUMN "orderNumber" TEXT`,
  `ALTER TABLE "InventoryStockLot" ADD COLUMN "transactionId" TEXT`,
  `ALTER TABLE "InventoryStockLot" ADD COLUMN "sourceStore" TEXT`,
  `ALTER TABLE "InventoryStockLot" ADD COLUMN "paymentMethod" TEXT`,
  `ALTER TABLE "BarcodeScan" ADD COLUMN "rawCode" TEXT`,
  `ALTER TABLE "BarcodeScan" ADD COLUMN "normalizedUpc" TEXT`,
  `ALTER TABLE "BarcodeScan" ADD COLUMN "variantsChecked" TEXT`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "firstOrderAt" DATETIME`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "customerAccountId" TEXT`,
  `ALTER TABLE "CustomerAccount" ADD COLUMN "normalizedEmail" TEXT`,
  `ALTER TABLE "CustomerAccount" ADD COLUMN "sessionRevokedBefore" DATETIME`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "lastOrderAt" DATETIME`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "totalOrders" INTEGER NOT NULL DEFAULT 0`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "totalSpent" REAL NOT NULL DEFAULT 0`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "defaultShippingName" TEXT`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "defaultShippingLine1" TEXT`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "defaultShippingLine2" TEXT`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "defaultShippingCity" TEXT`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "defaultShippingState" TEXT`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "defaultShippingPostalCode" TEXT`,
  `ALTER TABLE "StorefrontCustomer" ADD COLUMN "defaultShippingCountry" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "customerPhone" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "customerAccountId" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingName" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLine1" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLine2" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingCity" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingState" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingPostalCode" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingCountry" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "billingName" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "billingLine1" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "billingLine2" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "billingCity" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "billingState" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "billingPostalCode" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "billingCountry" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingMethodLabel" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingRateSource" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingPackageWeightOz" REAL`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingPackageLengthIn" REAL`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingPackageWidthIn" REAL`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingPackageHeightIn" REAL`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingPackageProfile" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingWarnings" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingQuoteId" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingQuoteProvider" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingCarrier" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingService" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingQuotedAmountCents" INTEGER`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingQuotedZip" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingQuoteFallbackUsed" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingQuoteRateProviderRef" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingQuoteShipmentProviderRef" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingQuoteExpiresAt" DATETIME`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingZipMismatchReview" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLabelProvider" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLabelProviderId" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLabelUrl" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLabelFileType" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingTrackingNumber" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingTrackingUrl" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLabelCostCents" INTEGER`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLabelCurrency" TEXT`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLabelPurchasedAt" DATETIME`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLabelVoidedAt" DATETIME`,
  `ALTER TABLE "StorefrontOrder" ADD COLUMN "shippingLabelStatus" TEXT`,
  `CREATE TABLE IF NOT EXISTS "ShippingQuote" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "quoteToken" TEXT NOT NULL UNIQUE,
    "userId" TEXT,
    "orderId" TEXT,
    "provider" TEXT NOT NULL,
    "carrier" TEXT NOT NULL,
    "service" TEXT NOT NULL,
    "amountCents" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "destinationZip" TEXT NOT NULL,
    "country" TEXT NOT NULL DEFAULT 'US',
    "packageWeightOz" REAL,
    "packageLengthIn" REAL,
    "packageWidthIn" REAL,
    "packageHeightIn" REAL,
    "packageProfileKey" TEXT,
    "rateProviderRef" TEXT,
    "shipmentProviderRef" TEXT,
    "fallbackUsed" BOOLEAN NOT NULL DEFAULT false,
    "warning" TEXT,
    "expiresAt" DATETIME NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "usedAt" DATETIME,
    "cartHash" TEXT,
    CONSTRAINT "ShippingQuote_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ShippingQuote_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "StorefrontOrder" ("id") ON DELETE SET NULL ON UPDATE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS "Product_retailerId_idx" ON "Product"("retailerId")`,
  `CREATE INDEX IF NOT EXISTS "Product_releaseId_idx" ON "Product"("releaseId")`,
  `CREATE INDEX IF NOT EXISTS "Product_setName_idx" ON "Product"("setName")`,
  `CREATE INDEX IF NOT EXISTS "Product_productType_idx" ON "Product"("productType")`,
  `CREATE INDEX IF NOT EXISTS "Product_upc_idx" ON "Product"("upc")`,
  `CREATE INDEX IF NOT EXISTS "Product_retailerProductId_idx" ON "Product"("retailerProductId")`,
  `CREATE INDEX IF NOT EXISTS "Product_verificationStatus_idx" ON "Product"("verificationStatus")`,
  `CREATE INDEX IF NOT EXISTS "PasswordResetToken_userId_idx" ON "PasswordResetToken"("userId")`,
  `CREATE INDEX IF NOT EXISTS "PasswordResetToken_expiresAt_idx" ON "PasswordResetToken"("expiresAt")`,
  `CREATE INDEX IF NOT EXISTS "PasswordResetToken_usedAt_idx" ON "PasswordResetToken"("usedAt")`,
  `CREATE INDEX IF NOT EXISTS "FriendInvite_email_idx" ON "FriendInvite"("email")`,
  `CREATE INDEX IF NOT EXISTS "FriendInvite_expiresAt_idx" ON "FriendInvite"("expiresAt")`,
  `CREATE INDEX IF NOT EXISTS "FriendInvite_acceptedAt_idx" ON "FriendInvite"("acceptedAt")`,
  `CREATE INDEX IF NOT EXISTS "FriendInvite_revokedAt_idx" ON "FriendInvite"("revokedAt")`,
  `CREATE INDEX IF NOT EXISTS "FriendInvite_createdById_idx" ON "FriendInvite"("createdById")`,
  `CREATE INDEX IF NOT EXISTS "FriendInvite_acceptedById_idx" ON "FriendInvite"("acceptedById")`,
  `CREATE INDEX IF NOT EXISTS "AuditLog_userId_idx" ON "AuditLog"("userId")`,
  `CREATE INDEX IF NOT EXISTS "AuditLog_action_idx" ON "AuditLog"("action")`,
  `CREATE INDEX IF NOT EXISTS "AuditLog_entityType_idx" ON "AuditLog"("entityType")`,
  `CREATE INDEX IF NOT EXISTS "AuditLog_createdAt_idx" ON "AuditLog"("createdAt")`,
  `CREATE INDEX IF NOT EXISTS "Product_stockStatus_idx" ON "Product"("stockStatus")`,
  `CREATE INDEX IF NOT EXISTS "Product_liveStockStatus_idx" ON "Product"("liveStockStatus")`,
  `CREATE INDEX IF NOT EXISTS "Product_sellerType_idx" ON "Product"("sellerType")`,
  `CREATE INDEX IF NOT EXISTS "Product_priceStatus_idx" ON "Product"("priceStatus")`,
  `CREATE INDEX IF NOT EXISTS "Product_alertEligibility_idx" ON "Product"("alertEligibility")`,
  `CREATE INDEX IF NOT EXISTS "Product_isDemoData_idx" ON "Product"("isDemoData")`,
  `CREATE INDEX IF NOT EXISTS "Product_archivedAt_idx" ON "Product"("archivedAt")`,
  `CREATE INDEX IF NOT EXISTS "Product_nextCheckAt_idx" ON "Product"("nextCheckAt")`,
  `CREATE INDEX IF NOT EXISTS "Product_monitorEnabled_idx" ON "Product"("monitorEnabled")`,
  `CREATE INDEX IF NOT EXISTS "Store_retailerId_idx" ON "Store"("retailerId")`,
  `CREATE INDEX IF NOT EXISTS "Store_zone_idx" ON "Store"("zone")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "UserStorePreference_userId_storeId_key" ON "UserStorePreference"("userId", "storeId")`,
  `CREATE INDEX IF NOT EXISTS "UserStorePreference_userId_idx" ON "UserStorePreference"("userId")`,
  `CREATE INDEX IF NOT EXISTS "UserStorePreference_storeId_idx" ON "UserStorePreference"("storeId")`,
  `CREATE INDEX IF NOT EXISTS "UserStorePreference_favorite_idx" ON "UserStorePreference"("favorite")`,
  `CREATE INDEX IF NOT EXISTS "UserStorePreference_hidden_idx" ON "UserStorePreference"("hidden")`,
  `CREATE INDEX IF NOT EXISTS "StoreSighting_storeId_idx" ON "StoreSighting"("storeId")`,
  `CREATE INDEX IF NOT EXISTS "StoreSighting_userId_idx" ON "StoreSighting"("userId")`,
  `CREATE INDEX IF NOT EXISTS "StoreSighting_resultType_idx" ON "StoreSighting"("resultType")`,
  `CREATE INDEX IF NOT EXISTS "StoreSighting_seenAt_idx" ON "StoreSighting"("seenAt")`,
  `CREATE INDEX IF NOT EXISTS "Alert_read_idx" ON "Alert"("read")`,
  `CREATE INDEX IF NOT EXISTS "Alert_priority_idx" ON "Alert"("priority")`,
  `CREATE INDEX IF NOT EXISTS "Alert_userId_idx" ON "Alert"("userId")`,
  `CREATE INDEX IF NOT EXISTS "Alert_score_idx" ON "Alert"("score")`,
  `CREATE INDEX IF NOT EXISTS "Alert_dedupeKey_idx" ON "Alert"("dedupeKey")`,
  `CREATE INDEX IF NOT EXISTS "Alert_falsePositiveAt_idx" ON "Alert"("falsePositiveAt")`,
  `CREATE INDEX IF NOT EXISTS "NotificationDeliveryLog_alertId_idx" ON "NotificationDeliveryLog"("alertId")`,
  `CREATE INDEX IF NOT EXISTS "NotificationDeliveryLog_userId_idx" ON "NotificationDeliveryLog"("userId")`,
  `CREATE INDEX IF NOT EXISTS "NotificationDeliveryLog_productId_idx" ON "NotificationDeliveryLog"("productId")`,
  `CREATE INDEX IF NOT EXISTS "NotificationDeliveryLog_channel_idx" ON "NotificationDeliveryLog"("channel")`,
  `CREATE INDEX IF NOT EXISTS "NotificationDeliveryLog_status_idx" ON "NotificationDeliveryLog"("status")`,
  `CREATE INDEX IF NOT EXISTS "NotificationDeliveryLog_createdAt_idx" ON "NotificationDeliveryLog"("createdAt")`,
  `CREATE INDEX IF NOT EXISTS "RestockHistory_productId_idx" ON "RestockHistory"("productId")`,
  `CREATE INDEX IF NOT EXISTS "RestockHistory_checkedAt_idx" ON "RestockHistory"("checkedAt")`,
  `CREATE INDEX IF NOT EXISTS "MonitorLog_productId_idx" ON "MonitorLog"("productId")`,
  `CREATE INDEX IF NOT EXISTS "MonitorLog_startedAt_idx" ON "MonitorLog"("startedAt")`,
  `CREATE INDEX IF NOT EXISTS "MonitorLog_status_idx" ON "MonitorLog"("status")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoverySource_retailerId_idx" ON "ProductDiscoverySource"("retailerId")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoverySource_enabled_idx" ON "ProductDiscoverySource"("enabled")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoverySource_nextCheckAt_idx" ON "ProductDiscoverySource"("nextCheckAt")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_sourceId_idx" ON "ProductDiscoveryCandidate"("sourceId")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_retailerId_idx" ON "ProductDiscoveryCandidate"("retailerId")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_status_idx" ON "ProductDiscoveryCandidate"("status")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_retailerProductId_idx" ON "ProductDiscoveryCandidate"("retailerProductId")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_upc_idx" ON "ProductDiscoveryCandidate"("upc")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_dpci_idx" ON "ProductDiscoveryCandidate"("dpci")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_sellerType_idx" ON "ProductDiscoveryCandidate"("sellerType")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_priceStatus_idx" ON "ProductDiscoveryCandidate"("priceStatus")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_alertEligibility_idx" ON "ProductDiscoveryCandidate"("alertEligibility")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_enrichmentStatus_idx" ON "ProductDiscoveryCandidate"("enrichmentStatus")`,
  `CREATE INDEX IF NOT EXISTS "ProductDiscoveryCandidate_createdAt_idx" ON "ProductDiscoveryCandidate"("createdAt")`,
  `CREATE INDEX IF NOT EXISTS "Card_releaseId_idx" ON "Card"("releaseId")`,
  `CREATE INDEX IF NOT EXISTS "Card_setName_idx" ON "Card"("setName")`,
  `CREATE INDEX IF NOT EXISTS "CardPriceSnapshot_cardId_idx" ON "CardPriceSnapshot"("cardId")`,
  `CREATE INDEX IF NOT EXISTS "CardPriceSnapshot_snapshotAt_idx" ON "CardPriceSnapshot"("snapshotAt")`,
  `CREATE INDEX IF NOT EXISTS "CardCompSale_cardId_idx" ON "CardCompSale"("cardId")`,
  `CREATE INDEX IF NOT EXISTS "CardCompSale_gradeType_idx" ON "CardCompSale"("gradeType")`,
  `CREATE INDEX IF NOT EXISTS "CardCompSale_sourceQuality_idx" ON "CardCompSale"("sourceQuality")`,
  `CREATE INDEX IF NOT EXISTS "CardCompSale_reviewStatus_idx" ON "CardCompSale"("reviewStatus")`,
  `CREATE INDEX IF NOT EXISTS "CardCompSale_soldAt_idx" ON "CardCompSale"("soldAt")`,
  `CREATE INDEX IF NOT EXISTS "CardCompSale_matchScore_idx" ON "CardCompSale"("matchScore")`,
  `CREATE INDEX IF NOT EXISTS "InvestmentReport_generatedAt_idx" ON "InvestmentReport"("generatedAt")`,
  `CREATE INDEX IF NOT EXISTS "InvestmentReport_userId_idx" ON "InvestmentReport"("userId")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_userId_idx" ON "InventoryItem"("userId")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_productId_idx" ON "InventoryItem"("productId")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_cardId_idx" ON "InventoryItem"("cardId")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_category_idx" ON "InventoryItem"("category")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_listingStatus_idx" ON "InventoryItem"("listingStatus")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_recommendedAction_idx" ON "InventoryItem"("recommendedAction")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "InventoryItem_publicSlug_key" ON "InventoryItem"("publicSlug")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_publishToStore_idx" ON "InventoryItem"("publishToStore")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_storeStatus_idx" ON "InventoryItem"("storeStatus")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_storefrontCategory_idx" ON "InventoryItem"("storefrontCategory")`,
  `CREATE INDEX IF NOT EXISTS "InventoryItem_purchasedAt_idx" ON "InventoryItem"("purchasedAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "InventoryProductImage_inventoryItemId_url_key" ON "InventoryProductImage"("inventoryItemId", "url")`,
  `CREATE INDEX IF NOT EXISTS "InventoryProductImage_inventoryItemId_idx" ON "InventoryProductImage"("inventoryItemId")`,
  `CREATE INDEX IF NOT EXISTS "InventoryProductImage_inventoryItemId_sortOrder_idx" ON "InventoryProductImage"("inventoryItemId", "sortOrder")`,
  `CREATE INDEX IF NOT EXISTS "InventoryProductImage_isPrimary_idx" ON "InventoryProductImage"("isPrimary")`,
  `CREATE INDEX IF NOT EXISTS "InventoryProductImage_showInStore_idx" ON "InventoryProductImage"("showInStore")`,
  `CREATE INDEX IF NOT EXISTS "InventoryStockLot_inventoryItemId_idx" ON "InventoryStockLot"("inventoryItemId")`,
  `CREATE INDEX IF NOT EXISTS "InventoryStockLot_purchasedAt_idx" ON "InventoryStockLot"("purchasedAt")`,
  `CREATE INDEX IF NOT EXISTS "InventoryStockLot_remainingQuantity_idx" ON "InventoryStockLot"("remainingQuantity")`,
  `CREATE INDEX IF NOT EXISTS "InventorySale_inventoryItemId_idx" ON "InventorySale"("inventoryItemId")`,
  `CREATE INDEX IF NOT EXISTS "InventorySale_userId_idx" ON "InventorySale"("userId")`,
  `CREATE INDEX IF NOT EXISTS "InventorySale_platform_idx" ON "InventorySale"("platform")`,
  `CREATE INDEX IF NOT EXISTS "InventorySale_soldAt_idx" ON "InventorySale"("soldAt")`,
  `CREATE INDEX IF NOT EXISTS "InventoryMarketComp_inventoryItemId_idx" ON "InventoryMarketComp"("inventoryItemId")`,
  `CREATE INDEX IF NOT EXISTS "InventoryMarketComp_sourceQuality_idx" ON "InventoryMarketComp"("sourceQuality")`,
  `CREATE INDEX IF NOT EXISTS "InventoryMarketComp_soldAt_idx" ON "InventoryMarketComp"("soldAt")`,
  `CREATE INDEX IF NOT EXISTS "BarcodeScan_userId_idx" ON "BarcodeScan"("userId")`,
  `CREATE INDEX IF NOT EXISTS "BarcodeScan_upc_idx" ON "BarcodeScan"("upc")`,
  `CREATE INDEX IF NOT EXISTS "BarcodeScan_rawCode_idx" ON "BarcodeScan"("rawCode")`,
  `CREATE INDEX IF NOT EXISTS "BarcodeScan_normalizedUpc_idx" ON "BarcodeScan"("normalizedUpc")`,
  `CREATE INDEX IF NOT EXISTS "BarcodeScan_createdAt_idx" ON "BarcodeScan"("createdAt")`,
  `CREATE INDEX IF NOT EXISTS "BarcodeScan_productId_idx" ON "BarcodeScan"("productId")`,
  `CREATE INDEX IF NOT EXISTS "BarcodeScan_inventoryItemId_idx" ON "BarcodeScan"("inventoryItemId")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontCustomer_userId_idx" ON "StorefrontCustomer"("userId")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontCustomer_customerAccountId_idx" ON "StorefrontCustomer"("customerAccountId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "StorefrontCustomer_email_key" ON "StorefrontCustomer"("email")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontCustomer_stripeCustomerId_idx" ON "StorefrontCustomer"("stripeCustomerId")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CustomerAccount_email_key" ON "CustomerAccount"("email")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAccount_userId_idx" ON "CustomerAccount"("userId")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAccount_email_idx" ON "CustomerAccount"("email")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAccount_normalizedEmail_idx" ON "CustomerAccount"("normalizedEmail")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAccount_status_idx" ON "CustomerAccount"("status")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAccount_sessionRevokedBefore_idx" ON "CustomerAccount"("sessionRevokedBefore")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAccount_emailVerifiedAt_idx" ON "CustomerAccount"("emailVerifiedAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CustomerSession_tokenHash_key" ON "CustomerSession"("tokenHash")`,
  `CREATE INDEX IF NOT EXISTS "CustomerSession_customerAccountId_idx" ON "CustomerSession"("customerAccountId")`,
  `CREATE INDEX IF NOT EXISTS "CustomerSession_lastActivityAt_idx" ON "CustomerSession"("lastActivityAt")`,
  `CREATE INDEX IF NOT EXISTS "CustomerSession_absoluteExpiresAt_idx" ON "CustomerSession"("absoluteExpiresAt")`,
  `CREATE INDEX IF NOT EXISTS "CustomerSession_revokedAt_idx" ON "CustomerSession"("revokedAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CustomerAuthRateLimit_action_emailKeyHash_clientKeyHash_windowStart_key" ON "CustomerAuthRateLimit"("action", "emailKeyHash", "clientKeyHash", "windowStart")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAuthRateLimit_action_idx" ON "CustomerAuthRateLimit"("action")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAuthRateLimit_emailKeyHash_idx" ON "CustomerAuthRateLimit"("emailKeyHash")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAuthRateLimit_clientKeyHash_idx" ON "CustomerAuthRateLimit"("clientKeyHash")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAuthRateLimit_windowStart_idx" ON "CustomerAuthRateLimit"("windowStart")`,
  `CREATE INDEX IF NOT EXISTS "CustomerAuthRateLimit_blockedUntil_idx" ON "CustomerAuthRateLimit"("blockedUntil")`,
  `CREATE INDEX IF NOT EXISTS "CustomerSavedAddress_customerAccountId_idx" ON "CustomerSavedAddress"("customerAccountId")`,
  `CREATE INDEX IF NOT EXISTS "CustomerSavedAddress_customerAccountId_isDefault_idx" ON "CustomerSavedAddress"("customerAccountId", "isDefault")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CustomerMagicLinkToken_tokenHash_key" ON "CustomerMagicLinkToken"("tokenHash")`,
  `CREATE INDEX IF NOT EXISTS "CustomerMagicLinkToken_customerAccountId_idx" ON "CustomerMagicLinkToken"("customerAccountId")`,
  `CREATE INDEX IF NOT EXISTS "CustomerMagicLinkToken_email_idx" ON "CustomerMagicLinkToken"("email")`,
  `CREATE INDEX IF NOT EXISTS "CustomerMagicLinkToken_expiresAt_idx" ON "CustomerMagicLinkToken"("expiresAt")`,
  `CREATE INDEX IF NOT EXISTS "CustomerMagicLinkToken_usedAt_idx" ON "CustomerMagicLinkToken"("usedAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "CustomerPasswordResetToken_tokenHash_key" ON "CustomerPasswordResetToken"("tokenHash")`,
  `CREATE INDEX IF NOT EXISTS "CustomerPasswordResetToken_customerAccountId_idx" ON "CustomerPasswordResetToken"("customerAccountId")`,
  `CREATE INDEX IF NOT EXISTS "CustomerPasswordResetToken_expiresAt_idx" ON "CustomerPasswordResetToken"("expiresAt")`,
  `CREATE INDEX IF NOT EXISTS "CustomerPasswordResetToken_usedAt_idx" ON "CustomerPasswordResetToken"("usedAt")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrder_userId_idx" ON "StorefrontOrder"("userId")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrder_customerId_idx" ON "StorefrontOrder"("customerId")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrder_customerAccountId_idx" ON "StorefrontOrder"("customerAccountId")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrder_status_idx" ON "StorefrontOrder"("status")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrder_paymentStatus_idx" ON "StorefrontOrder"("paymentStatus")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrder_fulfillmentStatus_idx" ON "StorefrontOrder"("fulfillmentStatus")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrder_refundStatus_idx" ON "StorefrontOrder"("refundStatus")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrder_createdAt_idx" ON "StorefrontOrder"("createdAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "ShippingQuote_quoteToken_key" ON "ShippingQuote"("quoteToken")`,
  `CREATE INDEX IF NOT EXISTS "ShippingQuote_userId_idx" ON "ShippingQuote"("userId")`,
  `CREATE INDEX IF NOT EXISTS "ShippingQuote_orderId_idx" ON "ShippingQuote"("orderId")`,
  `CREATE INDEX IF NOT EXISTS "ShippingQuote_expiresAt_idx" ON "ShippingQuote"("expiresAt")`,
  `CREATE INDEX IF NOT EXISTS "ShippingQuote_destinationZip_idx" ON "ShippingQuote"("destinationZip")`,
  `CREATE INDEX IF NOT EXISTS "ShippingQuote_cartHash_idx" ON "ShippingQuote"("cartHash")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrderItem_orderId_idx" ON "StorefrontOrderItem"("orderId")`,
  `CREATE INDEX IF NOT EXISTS "StorefrontOrderItem_inventoryItemId_idx" ON "StorefrontOrderItem"("inventoryItemId")`,
  `CREATE INDEX IF NOT EXISTS "StockReservation_inventoryItemId_idx" ON "StockReservation"("inventoryItemId")`,
  `CREATE INDEX IF NOT EXISTS "StockReservation_orderId_idx" ON "StockReservation"("orderId")`,
  `CREATE INDEX IF NOT EXISTS "StockReservation_stripeCheckoutSessionId_idx" ON "StockReservation"("stripeCheckoutSessionId")`,
  `CREATE INDEX IF NOT EXISTS "StockReservation_status_idx" ON "StockReservation"("status")`,
  `CREATE INDEX IF NOT EXISTS "StockReservation_expiresAt_idx" ON "StockReservation"("expiresAt")`,
  `CREATE INDEX IF NOT EXISTS "PaymentEvent_orderId_idx" ON "PaymentEvent"("orderId")`,
  `CREATE INDEX IF NOT EXISTS "PaymentEvent_eventType_idx" ON "PaymentEvent"("eventType")`,
  `CREATE INDEX IF NOT EXISTS "PaymentEvent_receivedAt_idx" ON "PaymentEvent"("receivedAt")`,
  `CREATE INDEX IF NOT EXISTS "RewardLedgerEntry_customerAccountId_idx" ON "RewardLedgerEntry"("customerAccountId")`,
  `CREATE INDEX IF NOT EXISTS "RewardLedgerEntry_orderId_idx" ON "RewardLedgerEntry"("orderId")`,
  `CREATE INDEX IF NOT EXISTS "RewardLedgerEntry_type_idx" ON "RewardLedgerEntry"("type")`,
  `CREATE INDEX IF NOT EXISTS "RewardLedgerEntry_createdAt_idx" ON "RewardLedgerEntry"("createdAt")`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "RewardLedgerEntry_idempotencyKey_key" ON "RewardLedgerEntry"("idempotencyKey")`,
  `CREATE INDEX IF NOT EXISTS "DailyRecap_userId_idx" ON "DailyRecap"("userId")`,
  `CREATE INDEX IF NOT EXISTS "DailyRecap_recapDate_idx" ON "DailyRecap"("recapDate")`,
  `CREATE INDEX IF NOT EXISTS "DailyRecap_createdAt_idx" ON "DailyRecap"("createdAt")`,
  `CREATE INDEX IF NOT EXISTS "SavedFilterPreset_userId_idx" ON "SavedFilterPreset"("userId")`,
  `CREATE INDEX IF NOT EXISTS "SavedFilterPreset_section_idx" ON "SavedFilterPreset"("section")`,
  `CREATE INDEX IF NOT EXISTS "ProductPriorityScore_productId_idx" ON "ProductPriorityScore"("productId")`,
  `CREATE INDEX IF NOT EXISTS "ProductPriorityScore_releaseId_idx" ON "ProductPriorityScore"("releaseId")`,
  `CREATE INDEX IF NOT EXISTS "BrowserPushSubscription_userId_idx" ON "BrowserPushSubscription"("userId")`,
  `CREATE INDEX IF NOT EXISTS "BrowserPushSubscription_disabledAt_idx" ON "BrowserPushSubscription"("disabledAt")`
];

function canIgnoreSqliteInitError(error: unknown) {
  if (!(error instanceof Error)) return false;
  return error.message.includes("duplicate column name") || error.message.includes("already exists");
}

async function main() {
  for (const statement of statements) {
    try {
      await prisma.$executeRawUnsafe(statement);
    } catch (error) {
      if (!canIgnoreSqliteInitError(error)) throw error;
    }
  }
  console.log("SQLite development database is ready.");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
